-- RA Copilot demo seed: Government Advisory Center
-- Generated by scripts/generate-seed.mjs — do not hand-edit, regenerate instead.
begin;

-- Organization --------------------------------------------------------
insert into public.organizations (id, name, name_ar, timezone, working_days, daily_work_hours, weekly_work_hours, target_utilization, overload_threshold)
values ('11111111-1111-1111-1111-111111111111', 'Government Advisory Center', 'مركز الاستشارات الحكومية', 'Asia/Riyadh', '[0,1,2,3,4]'::jsonb, 8, 40, 0.85, 0.90)
on conflict (id) do nothing;

-- Demo accounts (auth.users -> profiles is auto-provisioned by trigger) ------
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222201', 'authenticated', 'authenticated', 'admin@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Layla Al-Fahad","role":"admin","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222201', '22222222-2222-2222-2222-222222222201', '{"sub":"22222222-2222-2222-2222-222222222201","email":"admin@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222202', 'authenticated', 'authenticated', 'manager@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Abdulaziz Al-Nasser","role":"resource_manager","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222202', '22222222-2222-2222-2222-222222222202', '{"sub":"22222222-2222-2222-2222-222222222202","email":"manager@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222203', 'authenticated', 'authenticated', 'consultant@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Sara Al-Mutairi","role":"consultant","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222203', '22222222-2222-2222-2222-222222222203', '{"sub":"22222222-2222-2222-2222-222222222203","email":"consultant@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222204', 'authenticated', 'authenticated', 'executive@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Turki Al-Saud","role":"executive_viewer","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222204', '22222222-2222-2222-2222-222222222204', '{"sub":"22222222-2222-2222-2222-222222222204","email":"executive@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;

-- link the consultant demo login to its resource record once resources exist
-- (see end of file)

-- Skills ---------------------------------------------------------------
insert into public.skills (id, organization_id, name, category) values
  ('252d4d1f-8474-4a5e-8c92-5a96b15e93ab', '11111111-1111-1111-1111-111111111111', 'Strategy', 'Strategy'),
  ('f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', '11111111-1111-1111-1111-111111111111', 'Policy', 'Strategy'),
  ('b2c8de97-520b-4f49-8a07-c2045257a0b3', '11111111-1111-1111-1111-111111111111', 'Research', 'Analysis'),
  ('2d91a0cd-2cae-42b2-9be5-381d61a0cff0', '11111111-1111-1111-1111-111111111111', 'Benchmarking', 'Analysis'),
  ('40feffce-fd89-40d6-85ee-eb84b8861b7d', '11111111-1111-1111-1111-111111111111', 'Data Analysis', 'Data'),
  ('f903f9e9-b47f-4d60-923f-13a80f4b397f', '11111111-1111-1111-1111-111111111111', 'Power BI', 'Data'),
  ('0da732b5-e1b8-4e36-8144-37c8bf5bb333', '11111111-1111-1111-1111-111111111111', 'Financial Modeling', 'Finance'),
  ('fb99e48d-f99b-4212-8576-fa730dfafbec', '11111111-1111-1111-1111-111111111111', 'Economics', 'Finance'),
  ('e184b40f-dd92-496f-8c9b-0ad2db1af908', '11111111-1111-1111-1111-111111111111', 'Healthcare', 'Sector'),
  ('3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', '11111111-1111-1111-1111-111111111111', 'Digital Transformation', 'Strategy'),
  ('17e53c86-ac3d-4f96-9d0a-4e182593cc43', '11111111-1111-1111-1111-111111111111', 'Operating Model', 'Strategy'),
  ('b2b54461-576d-47d0-a2d6-b4d673ddef0e', '11111111-1111-1111-1111-111111111111', 'Process Improvement', 'Operations'),
  ('819a7096-33d1-4415-a83c-8d5132abf13f', '11111111-1111-1111-1111-111111111111', 'Project Management', 'Delivery'),
  ('2e84c1c3-8700-473e-849e-f0a87d0e0cbe', '11111111-1111-1111-1111-111111111111', 'Program Management', 'Delivery'),
  ('e7cf5519-564e-4a1e-96a7-aa2d8f845c78', '11111111-1111-1111-1111-111111111111', 'Stakeholder Management', 'Delivery'),
  ('1bcea6cc-b723-4fc9-b0ac-b33d20161629', '11111111-1111-1111-1111-111111111111', 'Presentation', 'Delivery'),
  ('44171332-a5ec-481a-88a4-1a0e733a7e24', '11111111-1111-1111-1111-111111111111', 'Quantitative Analysis', 'Analysis'),
  ('3ba88147-244b-4191-b657-fa1af6c87123', '11111111-1111-1111-1111-111111111111', 'Market Analysis', 'Analysis'),
  ('8eee5b95-3303-4b45-969b-78d2ffe7e837', '11111111-1111-1111-1111-111111111111', 'Business Analysis', 'Analysis'),
  ('34f8461d-6e0b-46a3-9fe9-297d3f063e08', '11111111-1111-1111-1111-111111111111', 'Change Management', 'Operations')
on conflict do nothing;

-- Resources --------------------------------------------------------------
insert into public.resources (id, organization_id, employee_code, full_name, job_title, department, seniority_level, weekly_capacity_hours, utilization_target, active) values
  ('ace286c0-7345-40a7-9c5c-67effd1a4b0f', '11111111-1111-1111-1111-111111111111', 'GAC-001', 'Sara Al-Mutairi', 'Consultant', 'Strategy & Transformation', 3, 40, 0.85, true),
  ('d4d6a4da-36e3-44c3-ab59-cfc37b923c5c', '11111111-1111-1111-1111-111111111111', 'GAC-002', 'Abdullah Al-Harbi', 'Senior Consultant', 'Data & Analytics', 4, 40, 0.85, true),
  ('02c3dea2-553e-4ad0-a0b3-56fa8003c493', '11111111-1111-1111-1111-111111111111', 'GAC-003', 'Noura Al-Qahtani', 'Senior Analyst', 'Policy & Research', 2, 40, 0.85, true),
  ('fee798aa-d69d-49f7-9b9d-d62d9b62402c', '11111111-1111-1111-1111-111111111111', 'GAC-004', 'Faisal Al-Otaibi', 'Principal Consultant', 'Economics', 5, 40, 0.85, true),
  ('d5c31e44-a16b-4690-92bf-92df9a691efe', '11111111-1111-1111-1111-111111111111', 'GAC-005', 'Maha Al-Zahrani', 'Consultant', 'Program Management', 3, 40, 0.85, true),
  ('d85ddb48-74d7-4223-a555-ec8ccb5cd9d8', '11111111-1111-1111-1111-111111111111', 'GAC-006', 'Khalid Al-Ghamdi', 'Senior Consultant', 'Sector Advisory', 4, 40, 0.85, true),
  ('34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', '11111111-1111-1111-1111-111111111111', 'GAC-007', 'Rana Al-Dosari', 'Senior Analyst', 'Strategy & Transformation', 2, 40, 0.85, true),
  ('c6f87582-3e5f-4d56-852d-759122e4b91b', '11111111-1111-1111-1111-111111111111', 'GAC-008', 'Omar Al-Balawi', 'Consultant', 'Data & Analytics', 3, 40, 0.85, true),
  ('3a1f98fc-0e4c-4347-a2dc-37edff1f489b', '11111111-1111-1111-1111-111111111111', 'GAC-009', 'Hind Al-Shammari', 'Senior Analyst', 'Executive Support', 2, 24, 0.85, true),
  ('a00da384-8fc9-4134-aad3-c90b306696fd', '11111111-1111-1111-1111-111111111111', 'GAC-010', 'Yousef Al-Anazi', 'Consultant', 'Policy & Research', 3, 40, 0.85, true),
  ('c2587a96-3099-4978-98c0-61181d242fe3', '11111111-1111-1111-1111-111111111111', 'GAC-011', 'Ahmed Al-Amri', 'Principal Consultant', 'Sector Advisory', 5, 40, 0.85, true),
  ('b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', '11111111-1111-1111-1111-111111111111', 'GAC-012', 'Reem Al-Subaie', 'Senior Analyst', 'Economics', 2, 40, 0.85, true),
  ('a8bc2041-f849-403e-b7ee-3bba019125ff', '11111111-1111-1111-1111-111111111111', 'GAC-013', 'Tariq Al-Qahtani', 'Senior Consultant', 'Program Management', 4, 40, 0.85, true),
  ('f4accce0-288f-42a0-8091-c6328ed617fc', '11111111-1111-1111-1111-111111111111', 'GAC-014', 'Dana Al-Harthi', 'Consultant', 'Strategy & Transformation', 3, 40, 0.85, true),
  ('e80df80d-f636-4458-8ed9-e8674e555db3', '11111111-1111-1111-1111-111111111111', 'GAC-015', 'Saud Al-Rashidi', 'Senior Analyst', 'Data & Analytics', 2, 40, 0.85, true),
  ('c6313b1a-4c1a-439a-85ab-6abf34799ab6', '11111111-1111-1111-1111-111111111111', 'GAC-016', 'Aisha Al-Malki', 'Senior Consultant', 'Policy & Research', 4, 40, 0.85, true),
  ('d03e82e3-8224-4c2b-bbb2-af1b60f59943', '11111111-1111-1111-1111-111111111111', 'GAC-017', 'Bandar Al-Juhani', 'Consultant', 'Sector Advisory', 3, 40, 0.85, true),
  ('a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', '11111111-1111-1111-1111-111111111111', 'GAC-018', 'Fatimah Al-Yami', 'Consultant', 'Economics', 3, 32, 0.85, true),
  ('a663ae9f-8faa-448a-bfaf-da2d142d5988', '11111111-1111-1111-1111-111111111111', 'GAC-019', 'Nasser Al-Otaibi', 'Senior Analyst', 'Program Management', 2, 40, 0.85, true),
  ('be7576fd-7580-462c-9409-8f0712f73b8c', '11111111-1111-1111-1111-111111111111', 'GAC-020', 'Wafa Al-Saleh', 'Consultant', 'Executive Support', 3, 40, 0.85, true),
  ('a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', '11111111-1111-1111-1111-111111111111', 'GAC-021', 'Majed Al-Shehri', 'Senior Consultant', 'Strategy & Transformation', 4, 40, 0.85, true),
  ('a0d0e5c2-0712-4640-8adf-23943c987cc7', '11111111-1111-1111-1111-111111111111', 'GAC-022', 'Amal Al-Qarni', 'Consultant', 'Data & Analytics', 3, 40, 0.85, true),
  ('f7215d4d-ef59-417b-a156-1435ea1d215a', '11111111-1111-1111-1111-111111111111', 'GAC-023', 'Sultan Al-Mansour', 'Senior Analyst', 'Sector Advisory', 2, 40, 0.85, true),
  ('251af3b0-0dde-4980-a298-cda972507739', '11111111-1111-1111-1111-111111111111', 'GAC-024', 'Haya Al-Dossary', 'Analyst', 'Policy & Research', 1, 40, 0.85, true),
  ('bb38b2b2-7489-42b3-9728-f79cd087b758', '11111111-1111-1111-1111-111111111111', 'GAC-025', 'Rashid Al-Ateeqi', 'Consultant', 'Program Management', 3, 40, 0.85, true),
  ('74833da1-3203-42f5-9eb0-cffa25072399', '11111111-1111-1111-1111-111111111111', 'GAC-026', 'Nawaf Al-Buqami', 'Analyst', 'Economics', 1, 40, 0.85, false)
on conflict do nothing;

-- Tie the consultant demo account to its resource profile ---------------
update public.profiles set resource_id = 'ace286c0-7345-40a7-9c5c-67effd1a4b0f' where id = '22222222-2222-2222-2222-222222222203';

-- Resource skills ---------------------------------------------------------
insert into public.resource_skills (id, organization_id, resource_id, skill_id, proficiency, years_experience, verified) values
  ('fadc5e35-1d25-418d-9016-d0f0bd9c5291', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 4, 5.0, true),
  ('499b505f-d727-44dc-9163-0f1cd921c66e', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 4, 5.4, false),
  ('a7f96b06-0360-46c9-9fde-c8825aaae4e9', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', '34f8461d-6e0b-46a3-9fe9-297d3f063e08', 4, 6.0, false),
  ('fc51b7a3-581f-456f-82d6-32a44b8f65fb', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 3, 5.5, true),
  ('e4e696b0-ad22-449c-9422-d7ca538b8432', '11111111-1111-1111-1111-111111111111', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 5, 6.1, false),
  ('42095791-041e-4b93-92ce-ed17d3fa68f6', '11111111-1111-1111-1111-111111111111', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', '44171332-a5ec-481a-88a4-1a0e733a7e24', 4, 6.4, true),
  ('edbb8e71-60ea-4d0c-9471-0bb130f25d35', '11111111-1111-1111-1111-111111111111', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 5, 6.1, false),
  ('d3a21665-2a29-4659-bf30-f4865744466d', '11111111-1111-1111-1111-111111111111', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'f903f9e9-b47f-4d60-923f-13a80f4b397f', 5, 7.0, true),
  ('febc8d37-71e6-41ef-b072-8b4d7c1b83b8', '11111111-1111-1111-1111-111111111111', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 3, 4.2, false),
  ('03552b03-743c-4cac-a106-9dd45ff2c36e', '11111111-1111-1111-1111-111111111111', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', 'f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', 3, 3.4, false),
  ('459770fa-d7bd-450a-ac1f-251cf8dd8c84', '11111111-1111-1111-1111-111111111111', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 4.7, true),
  ('6f75f3f1-0b75-4a72-8d00-d9b4548cacd3', '11111111-1111-1111-1111-111111111111', 'fee798aa-d69d-49f7-9b9d-d62d9b62402c', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 5, 8.9, true),
  ('d98f759f-8a34-4011-941e-5ef08f3c6bb0', '11111111-1111-1111-1111-111111111111', 'fee798aa-d69d-49f7-9b9d-d62d9b62402c', '3ba88147-244b-4191-b657-fa1af6c87123', 5, 7.7, true),
  ('d0f9448a-f7b3-4b8d-a5dd-a1095c194134', '11111111-1111-1111-1111-111111111111', 'fee798aa-d69d-49f7-9b9d-d62d9b62402c', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 5, 9.4, false),
  ('4e5a25c2-81a6-4826-9d02-4c7e5ffeb470', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', '819a7096-33d1-4415-a83c-8d5132abf13f', 4, 6.3, false),
  ('6a4dce4e-84e9-45a0-ad4c-3e44386c7831', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 6.4, false),
  ('b1e71399-d74a-4279-add0-299b90e6483e', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 4, 4.9, true),
  ('da2d53d3-c6ff-4738-9c98-c3e4284c6a3e', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'e184b40f-dd92-496f-8c9b-0ad2db1af908', 5, 6.7, true),
  ('6bc12d30-3d27-4e05-acc3-253b4d630620', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 7.5, false),
  ('06099142-a209-4ae6-a3a8-d06a32ad73a3', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', '3ba88147-244b-4191-b657-fa1af6c87123', 4, 7.7, true),
  ('7a142cf3-7349-414a-bf33-be98f852c8a9', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 5, 7.8, true),
  ('4a57aa96-726d-444a-8a0f-d607414b2ff0', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 5, 6.6, false),
  ('76d68ad5-3238-4549-9a27-cf3b8b1971e6', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', '17e53c86-ac3d-4f96-9d0a-4e182593cc43', 3, 3.3, true),
  ('e805f042-2a4e-4add-bd21-e5c98c06e1ed', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 2, 4.4, true),
  ('9567e9cb-0cbb-416c-a618-31395dc9577d', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 2, 3.8, false),
  ('2b7d69cc-f70b-49c0-bc92-b012b787b3fe', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 3, 3.7, false),
  ('6e424d68-bab7-4e33-9731-839e5aa2afce', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 3, 4.8, false),
  ('6d632e48-d1dd-4c59-92bb-b4f08eca2eaf', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'f903f9e9-b47f-4d60-923f-13a80f4b397f', 4, 5.8, true),
  ('b21b7252-2a2a-410e-aa9c-465f258e69c4', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 4, 4.9, true),
  ('2b51807b-e490-4bc5-b2c2-7aed2157a052', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 3, 4.9, false),
  ('c5f93003-5888-4913-9a0f-4f8fa3d63456', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', '44171332-a5ec-481a-88a4-1a0e733a7e24', 4, 5.9, false),
  ('ad3f9446-91a5-45ce-b131-a9b6ab88beb3', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 3, 5.2, false),
  ('2f2d8e86-94bd-4961-9aa5-b60ea0f490ba', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 2, 3.3, true),
  ('38d250ba-1303-4116-b47a-1f3a7d20c659', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 2, 3.8, true),
  ('7e273ca6-a9b6-417a-8aa8-75bf08cdcffe', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', '2e84c1c3-8700-473e-849e-f0a87d0e0cbe', 2, 4.4, false),
  ('c03e9e64-21a1-49e6-9ec9-dc05bdb10881', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 5.7, false),
  ('7af78a75-674a-4df7-965a-2f30ef9ead2a', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 5.1, false),
  ('f24d0236-c462-4b8b-88dc-0e5b871ee6dd', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 4, 4.9, false),
  ('2db41a51-773c-4d54-93bd-30220211f7b0', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '44171332-a5ec-481a-88a4-1a0e733a7e24', 4, 5.1, false),
  ('23bed277-9170-48da-bcf2-79a17f9be069', '11111111-1111-1111-1111-111111111111', 'c2587a96-3099-4978-98c0-61181d242fe3', 'e184b40f-dd92-496f-8c9b-0ad2db1af908', 5, 8.3, true),
  ('4f02fef9-05d2-49bb-a718-b136a38a1c38', '11111111-1111-1111-1111-111111111111', 'c2587a96-3099-4978-98c0-61181d242fe3', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 5, 9.1, true),
  ('ef6d937c-8208-4815-90a2-0182c4aec425', '11111111-1111-1111-1111-111111111111', 'c2587a96-3099-4978-98c0-61181d242fe3', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 5, 9.2, true),
  ('4f266a16-cba9-4dc7-90a3-49266c02ae53', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 2, 3.8, true),
  ('f97e3204-2819-4f1f-a2c0-8897097b1066', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 3, 4.0, true),
  ('b7d8a8d5-6f22-46b6-9b3c-cf4acc3e3547', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 3, 4.5, false),
  ('3e906515-ac3f-4db2-8f8a-1dcfabaa45ad', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', '44171332-a5ec-481a-88a4-1a0e733a7e24', 2, 3.3, true),
  ('6a323369-fd4f-4454-b6a4-f5cc181917fe', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', '3ba88147-244b-4191-b657-fa1af6c87123', 3, 4.5, true),
  ('af7a0bfa-24f9-406a-b9f6-fd90d0e2522d', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 4, 7.8, true),
  ('85c14cfd-20ba-49aa-8310-8a4955e61536', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 4, 7.9, true),
  ('b151d49f-a921-49ac-b37e-2e58ccbca66d', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 7.7, false),
  ('36120366-9641-4123-900f-521546ee22b1', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', '2e84c1c3-8700-473e-849e-f0a87d0e0cbe', 4, 6.0, false),
  ('f27a72a9-eb94-41da-9d51-f8c66418d6f5', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', '819a7096-33d1-4415-a83c-8d5132abf13f', 5, 7.5, true),
  ('5fe196da-7ad2-4191-b7ad-4b0e551ab1fc', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 3, 5.1, true),
  ('8a0c15b7-9eb5-4a1d-962d-1bbbb1120936', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 5.9, true),
  ('b2268010-b373-4033-9927-c04397334269', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 4, 4.9, true),
  ('357cd8e9-0c45-452b-98f1-e4dd79542b23', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', '17e53c86-ac3d-4f96-9d0a-4e182593cc43', 4, 5.4, true),
  ('d0b4d7a5-2a83-4f91-9be7-386e31801131', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', '34f8461d-6e0b-46a3-9fe9-297d3f063e08', 3, 5.4, false),
  ('220f8004-0464-428a-9581-8881350f9c00', '11111111-1111-1111-1111-111111111111', 'e80df80d-f636-4458-8ed9-e8674e555db3', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 3, 4.1, true),
  ('495c3efb-1576-46a8-b0c7-20dcd491858a', '11111111-1111-1111-1111-111111111111', 'e80df80d-f636-4458-8ed9-e8674e555db3', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 2, 3.3, false),
  ('bece2f06-1410-4e94-8274-0a61218c9116', '11111111-1111-1111-1111-111111111111', 'e80df80d-f636-4458-8ed9-e8674e555db3', 'f903f9e9-b47f-4d60-923f-13a80f4b397f', 2, 4.9, false),
  ('b9f94286-0f41-434e-9158-2a0c75134cd1', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 4, 6.5, true),
  ('9d12a515-616b-44ad-8964-95ad89b7ee9d', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', '44171332-a5ec-481a-88a4-1a0e733a7e24', 5, 6.2, true),
  ('518eb1b0-ca8f-4ad4-9985-b7377ab8a053', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', 5, 7.3, true),
  ('6c8214d0-a7fe-4763-93a6-05738dc1cbd0', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 5, 7.6, true),
  ('d4858f3a-e25f-42d8-9ec8-bb0b594d4f40', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 4, 6.2, false),
  ('6319d0fa-180f-4788-b7b1-29d9e2473cb0', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 4, 6.5, false),
  ('67ca44f6-d9b9-4180-8429-e2b41a2fb00a', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 3, 5.2, false),
  ('b673a85e-2cef-49b4-ac61-ba75c7c99749', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 5.6, false),
  ('88083402-43dc-432c-8a6a-2b87aaa4ff69', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 4, 5.6, true),
  ('aa5b7761-c340-40df-9db5-95261bbe2c70', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 3, 5.5, true),
  ('e373cc39-9414-4abe-853a-404ec35109ae', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', '3ba88147-244b-4191-b657-fa1af6c87123', 4, 5.9, true),
  ('58e76498-e0cd-4230-8d9d-e95224cdc439', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', '44171332-a5ec-481a-88a4-1a0e733a7e24', 4, 6.4, true),
  ('73d3b1b4-13dc-4075-b9ee-35975c5af11f', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 4, 5.1, true),
  ('35381a5d-a6e5-44d1-9db8-756edc283903', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 2, 3.7, true),
  ('81707587-4f84-4488-a526-cf3bb0d62310', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', '2e84c1c3-8700-473e-849e-f0a87d0e0cbe', 3, 4.2, true),
  ('e6ef6b5e-5e7e-4692-a9f0-e1054a5e1ed6', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 3, 3.3, false),
  ('a422a572-140f-4204-abea-add8ba0b33ce', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', '819a7096-33d1-4415-a83c-8d5132abf13f', 3, 4.0, false),
  ('0840ec81-3e9a-4efa-9f8a-d0dbec9d2168', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 4.5, true),
  ('8a55583e-0bcd-4900-8804-682e8a8c4f39', '11111111-1111-1111-1111-111111111111', 'be7576fd-7580-462c-9409-8f0712f73b8c', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 4.6, true),
  ('149aa24b-a22f-4a31-a7cf-c01c008e286c', '11111111-1111-1111-1111-111111111111', 'be7576fd-7580-462c-9409-8f0712f73b8c', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 4, 5.9, true),
  ('9b23e2a2-3888-4a88-a9dc-8b8e5137296a', '11111111-1111-1111-1111-111111111111', 'be7576fd-7580-462c-9409-8f0712f73b8c', '2e84c1c3-8700-473e-849e-f0a87d0e0cbe', 3, 5.7, true),
  ('82f4f561-732a-4f42-b953-084f03bfb823', '11111111-1111-1111-1111-111111111111', 'be7576fd-7580-462c-9409-8f0712f73b8c', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 4.6, false),
  ('4844b1de-11f8-4d6d-9ae8-e50366d309c7', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 5, 7.4, false),
  ('cdacf896-21f3-489a-97d8-da31844b440a', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 4, 6.5, true),
  ('1a6c4ca1-5f85-4b70-8caa-28fe6a50a510', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 4, 7.7, true),
  ('7e00d3fa-61c4-44ed-abcd-deea1ad6c3b3', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 3, 5.1, false),
  ('9d328936-0ba6-42fd-ad97-7e117e35aba9', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'f903f9e9-b47f-4d60-923f-13a80f4b397f', 4, 5.5, true),
  ('e837fccb-498d-4704-ae46-dc385a61cc6c', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 4, 4.7, true),
  ('509de278-1416-49ce-b2ad-c74470423a23', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 4, 6.3, false),
  ('876c2e1b-531f-4e38-8dff-1f17479b5555', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', '44171332-a5ec-481a-88a4-1a0e733a7e24', 3, 4.6, false),
  ('e68694e6-a5f9-49b8-9382-369e60e9e6df', '11111111-1111-1111-1111-111111111111', 'f7215d4d-ef59-417b-a156-1435ea1d215a', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 3, 3.7, true),
  ('f093604d-3c3f-476e-9ce0-3a601fc50be8', '11111111-1111-1111-1111-111111111111', 'f7215d4d-ef59-417b-a156-1435ea1d215a', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 2, 4.5, true),
  ('8f7ae496-c43b-4b23-bb1d-55531fd47427', '11111111-1111-1111-1111-111111111111', 'f7215d4d-ef59-417b-a156-1435ea1d215a', '3ba88147-244b-4191-b657-fa1af6c87123', 2, 3.4, true),
  ('74bd0e26-62d7-4ac4-95f1-38b23c46f61e', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', 2, 3.1, true),
  ('6b8ac186-3906-48c0-a437-4127a4a65fcb', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 2, 1.9, false),
  ('ec0710a8-154c-47b4-97ac-446d93f5ffc8', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 2, 2.8, false),
  ('57ea9987-6c78-4304-ae0e-7fa12a3e6b17', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', '44171332-a5ec-481a-88a4-1a0e733a7e24', 2, 2.0, false),
  ('b8c4a228-05e5-48cd-b61b-5416fde1bf62', '11111111-1111-1111-1111-111111111111', 'bb38b2b2-7489-42b3-9728-f79cd087b758', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 4, 6.0, false),
  ('5ff31c35-1434-464b-a45a-0d8c88627c02', '11111111-1111-1111-1111-111111111111', 'bb38b2b2-7489-42b3-9728-f79cd087b758', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 4, 5.7, false),
  ('04f18e72-7cf5-4ff6-a261-6f96c1318a35', '11111111-1111-1111-1111-111111111111', 'bb38b2b2-7489-42b3-9728-f79cd087b758', '819a7096-33d1-4415-a83c-8d5132abf13f', 3, 5.2, true),
  ('12a84d6b-3fc5-463c-be74-1196f4dd40ae', '11111111-1111-1111-1111-111111111111', 'bb38b2b2-7489-42b3-9728-f79cd087b758', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 4, 5.0, true),
  ('b978ef52-7560-4e10-8ac3-ac78194c39c1', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 2, 1.7, false),
  ('99cdb4d2-fc3b-46c8-bc37-92dcf86013dd', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', '44171332-a5ec-481a-88a4-1a0e733a7e24', 2, 1.9, true),
  ('2ddb744b-a9d2-46cd-a1be-3523dafa691d', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', '3ba88147-244b-4191-b657-fa1af6c87123', 2, 2.7, true),
  ('5962c68a-61f5-4f88-b7f6-f7825834de19', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 2, 1.8, true)
on conflict do nothing;

-- Historical projects ------------------------------------------------------
insert into public.historical_projects (id, organization_id, resource_id, project_name, sector, project_type, start_date, end_date, performance_score) values
  ('91044603-d973-45d8-9188-afc3fb53614d', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', 'Education Economic Study Engagement 0-0', 'Finance', 'Operating Model', '2025-09-16', '2025-12-03', 77),
  ('b9f6f51a-d35d-4b8f-abe8-d311be876049', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', 'Energy Benchmarking Engagement 0-1', 'Finance', 'Benchmarking', '2025-07-02', '2025-09-03', 84),
  ('4e25a51b-132d-41cc-997b-a2b3181ab093', '11111111-1111-1111-1111-111111111111', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', 'Healthcare Transformation Engagement 0-2', 'Digital Government', 'Economic Study', '2026-02-16', '2026-06-15', 92),
  ('0b119fd9-12d8-4a74-a5ff-218cc14991e8', '11111111-1111-1111-1111-111111111111', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'Finance Operating Model Engagement 1-0', 'Finance', 'Operating Model', '2025-05-19', '2025-09-05', 86),
  ('5d2c858e-c890-4351-940e-7b7b464ae87e', '11111111-1111-1111-1111-111111111111', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', 'Digital Government Strategy Engagement 2-0', 'Finance', 'Economic Study', '2025-03-19', '2025-05-18', 96),
  ('c8e14ef5-fca2-4c3a-a6f4-fcd4ba5538ca', '11111111-1111-1111-1111-111111111111', 'fee798aa-d69d-49f7-9b9d-d62d9b62402c', 'Finance Strategy Engagement 3-0', 'Education', 'Operating Model', '2025-05-03', '2025-09-21', 82),
  ('b9d207d1-40cb-41b6-a8ce-aa2b51653e8e', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'Digital Government Operating Model Engagement 5-0', 'Energy', 'Transformation', '2025-02-25', '2025-05-06', 83),
  ('ba5f9617-0b64-4201-8fb1-640b134f383e', '11111111-1111-1111-1111-111111111111', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'Healthcare Operating Model Engagement 5-1', 'Finance', 'Economic Study', '2026-03-04', '2026-07-23', 85),
  ('9e2255ca-396d-40aa-99d3-f73382b71e9e', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', 'Energy Transformation Engagement 6-0', 'Energy', 'Transformation', '2025-01-07', '2025-05-06', 96),
  ('c3700821-0d31-41d7-91cf-96e4d912a917', '11111111-1111-1111-1111-111111111111', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', 'Healthcare Transformation Engagement 6-1', 'Healthcare', 'Operating Model', '2025-01-27', '2025-04-11', 94),
  ('37ae4693-3f99-4814-8508-75cfe04d290d', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'Energy Operating Model Engagement 7-0', 'Energy', 'Economic Study', '2025-02-13', '2025-05-13', 77),
  ('47b5a0ae-4904-4bdf-bc7b-8d1b3907f13c', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'Digital Government Strategy Engagement 7-1', 'Healthcare', 'Benchmarking', '2025-12-20', '2026-03-23', 87),
  ('ce5b6f70-a663-43e1-b6ce-8b042e2ab240', '11111111-1111-1111-1111-111111111111', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'Energy Operating Model Engagement 7-2', 'Digital Government', 'Economic Study', '2025-09-02', '2025-12-28', 70),
  ('57cf9d22-5f23-4f3a-9a1b-92ab2007376c', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', 'Education Transformation Engagement 8-0', 'Finance', 'Benchmarking', '2024-12-26', '2025-03-18', 93),
  ('4c9a871b-7ea9-4996-a65d-1c8c3c15f5f7', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', 'Finance Operating Model Engagement 8-1', 'Energy', 'Strategy', '2025-04-27', '2025-07-24', 86),
  ('4c6d4130-a7fb-411d-b737-89e914a154d2', '11111111-1111-1111-1111-111111111111', '3a1f98fc-0e4c-4347-a2dc-37edff1f489b', 'Digital Government Operating Model Engagement 8-2', 'Education', 'Transformation', '2026-01-30', '2026-05-27', 80),
  ('85446a10-4eae-43a3-9445-559095d372ac', '11111111-1111-1111-1111-111111111111', 'c2587a96-3099-4978-98c0-61181d242fe3', 'Transport Economic Study Engagement 10-0', 'Digital Government', 'Operating Model', '2025-12-14', '2026-05-10', 85),
  ('1db08cfd-ffab-4cbd-86f9-3666be7cdd97', '11111111-1111-1111-1111-111111111111', 'c2587a96-3099-4978-98c0-61181d242fe3', 'Digital Government Strategy Engagement 10-1', 'Healthcare', 'Strategy', '2025-04-27', '2025-09-14', 95),
  ('fdbcefc6-56f1-492b-9bcc-e6d7945c39e5', '11111111-1111-1111-1111-111111111111', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', 'Healthcare Economic Study Engagement 11-0', 'Education', 'Strategy', '2026-02-19', '2026-06-06', 81),
  ('715c415e-6efc-41e6-b710-bad616b90cf8', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'Digital Government Economic Study Engagement 12-0', 'Healthcare', 'Economic Study', '2025-09-17', '2025-12-03', 86),
  ('3842176b-7ad1-46a8-a96c-17ff669ae91c', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'Finance Operating Model Engagement 12-1', 'Finance', 'Operating Model', '2025-01-07', '2025-04-29', 75),
  ('8ff90b85-061e-4b38-84ae-de81e0b24e95', '11111111-1111-1111-1111-111111111111', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'Digital Government Benchmarking Engagement 12-2', 'Energy', 'Transformation', '2025-12-31', '2026-05-03', 82),
  ('0abf262a-aadb-49fd-9217-e962c4420d30', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', 'Energy Transformation Engagement 13-0', 'Digital Government', 'Benchmarking', '2025-09-20', '2026-01-17', 95),
  ('a0137594-d519-4713-a108-26f30d2c2434', '11111111-1111-1111-1111-111111111111', 'f4accce0-288f-42a0-8091-c6328ed617fc', 'Transport Strategy Engagement 13-1', 'Transport', 'Transformation', '2025-06-27', '2025-11-16', 84),
  ('73e4f6d4-3aaf-42b7-8ad2-8156bf2fda78', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'Education Transformation Engagement 15-0', 'Transport', 'Transformation', '2026-02-26', '2026-06-24', 76),
  ('6be4b2cd-9e81-49ae-86f2-7e3e2d0fc377', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'Education Benchmarking Engagement 15-1', 'Transport', 'Benchmarking', '2024-11-21', '2025-02-16', 96),
  ('3df3f1a9-e8c8-464f-8ce2-3584c4d3561a', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'Education Benchmarking Engagement 15-2', 'Finance', 'Strategy', '2025-04-29', '2025-07-26', 85),
  ('24950165-d782-4ea3-bebb-6de1167259f9', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'Energy Operating Model Engagement 16-0', 'Energy', 'Operating Model', '2025-04-13', '2025-07-30', 87),
  ('3f9650a4-2d30-4f05-aaf0-af2d636ab50f', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'Education Economic Study Engagement 16-1', 'Finance', 'Strategy', '2025-07-24', '2025-11-13', 70),
  ('b1ea09aa-66b6-43f6-adef-59039c7f2be7', '11111111-1111-1111-1111-111111111111', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'Transport Strategy Engagement 16-2', 'Healthcare', 'Economic Study', '2025-03-18', '2025-06-20', 77),
  ('38d3c35d-760e-4d68-a687-d0a73077ca7f', '11111111-1111-1111-1111-111111111111', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', 'Healthcare Economic Study Engagement 17-0', 'Transport', 'Benchmarking', '2025-07-22', '2025-11-21', 87),
  ('fcf9c623-3c6d-4d1e-acf1-06e931fe66d1', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', 'Finance Transformation Engagement 18-0', 'Healthcare', 'Strategy', '2025-09-15', '2026-01-08', 79),
  ('211a4e10-3438-4555-be41-f7d3d5f4c0a6', '11111111-1111-1111-1111-111111111111', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', 'Energy Operating Model Engagement 18-1', 'Transport', 'Economic Study', '2024-12-21', '2025-05-07', 87),
  ('e34016b4-5fd1-48b9-a65c-6367ebc9be9a', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'Finance Strategy Engagement 20-0', 'Energy', 'Operating Model', '2024-11-23', '2025-02-27', 74),
  ('f38b0f67-4c29-4fa8-a7ee-f9b2ee5729c0', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'Healthcare Operating Model Engagement 20-1', 'Education', 'Operating Model', '2026-02-19', '2026-07-06', 97),
  ('be33ab94-9b6b-484b-bcbd-79203e15f48b', '11111111-1111-1111-1111-111111111111', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'Education Transformation Engagement 20-2', 'Energy', 'Strategy', '2025-06-19', '2025-10-17', 76),
  ('1f469d39-3035-49e9-bd65-8932fec9051c', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'Education Operating Model Engagement 21-0', 'Transport', 'Benchmarking', '2025-08-27', '2025-12-28', 79),
  ('d95172be-862f-4dd1-a2ec-8543dbedbda4', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'Energy Benchmarking Engagement 21-1', 'Education', 'Operating Model', '2025-04-20', '2025-09-05', 84),
  ('f88c668a-b6a7-43ba-9f4d-a1bbd4b21661', '11111111-1111-1111-1111-111111111111', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'Finance Transformation Engagement 21-2', 'Transport', 'Operating Model', '2025-03-09', '2025-06-28', 71),
  ('e2c87264-7965-48f3-97fc-e714e796907e', '11111111-1111-1111-1111-111111111111', 'f7215d4d-ef59-417b-a156-1435ea1d215a', 'Finance Economic Study Engagement 22-0', 'Education', 'Operating Model', '2026-02-12', '2026-04-23', 80),
  ('57e81e48-bb70-43c5-9f5c-161ab9c75158', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'Finance Economic Study Engagement 23-0', 'Transport', 'Operating Model', '2025-03-11', '2025-06-18', 77),
  ('e9590cf0-bc36-49e7-8ea8-b0fb4c3baa5f', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'Finance Strategy Engagement 23-1', 'Energy', 'Strategy', '2026-01-11', '2026-05-26', 91),
  ('122caa7a-ba2b-4440-9e88-222c71ec1cce', '11111111-1111-1111-1111-111111111111', '251af3b0-0dde-4980-a298-cda972507739', 'Education Transformation Engagement 23-2', 'Transport', 'Transformation', '2025-05-25', '2025-07-29', 76),
  ('467aa8e4-5b01-4cfd-b726-bc5018b6f682', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', 'Healthcare Benchmarking Engagement 25-0', 'Healthcare', 'Benchmarking', '2025-07-26', '2025-10-31', 83),
  ('ab37be93-97e6-4020-a6c8-00604d47e2a5', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', 'Energy Economic Study Engagement 25-1', 'Transport', 'Strategy', '2025-08-20', '2025-10-20', 75),
  ('6773432f-ad02-449d-b190-7e6d66743e12', '11111111-1111-1111-1111-111111111111', '74833da1-3203-42f5-9eb0-cffa25072399', 'Energy Transformation Engagement 25-2', 'Energy', 'Benchmarking', '2025-03-29', '2025-08-07', 89)
on conflict do nothing;

-- Resource availability (leave / training) --------------------------------
insert into public.resource_availability (id, organization_id, resource_id, date, available_hours, reason, availability_type) values
  ('82fb5e9f-1406-4e10-a712-b71f093ffe30', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', '2026-09-09', 0, 'Annual leave', 'leave'),
  ('7ed063d2-eea1-4f5e-b406-3dd6cf694a72', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', '2026-09-10', 0, 'Annual leave', 'leave'),
  ('1d9dc1f7-c650-4135-9cf2-71e30ea193b6', '11111111-1111-1111-1111-111111111111', 'd5c31e44-a16b-4690-92bf-92df9a691efe', '2026-09-13', 0, 'Annual leave', 'leave'),
  ('5c846cb5-86c7-4492-966f-4a3df3bc4b95', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2026-09-13', 0, 'Annual leave', 'leave'),
  ('430e376d-ec63-4a39-b123-bd1dc9ba5862', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2026-09-14', 0, 'Annual leave', 'leave'),
  ('f37eeda0-5e82-4acb-8a4b-4e970460022f', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2026-09-15', 0, 'Annual leave', 'leave'),
  ('110895e0-6216-4dbe-9749-c6ce10b5e39c', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2026-09-16', 0, 'Annual leave', 'leave'),
  ('cd8afceb-8aa2-45d0-8a69-68f99e492c2e', '11111111-1111-1111-1111-111111111111', 'a00da384-8fc9-4134-aad3-c90b306696fd', '2026-09-17', 0, 'Annual leave', 'leave'),
  ('5490e28a-f830-4e41-9bc5-08d4514c033e', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', '2026-09-17', 0, 'Annual leave', 'leave'),
  ('c21c90dd-becb-47d5-8d34-9169ddd31c33', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', '2026-09-20', 0, 'Annual leave', 'leave'),
  ('2bdc3f62-191d-412a-9acb-39839cef5fe4', '11111111-1111-1111-1111-111111111111', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', '2026-09-21', 0, 'Annual leave', 'leave'),
  ('4b4a4597-178b-44bf-8c2b-05dbe95a3ece', '11111111-1111-1111-1111-111111111111', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', '2026-09-07', 4, 'Government Excellence Program training', 'training')
on conflict do nothing;

-- Work requests -------------------------------------------------------------
insert into public.work_requests (id, organization_id, request_number, title, description, requesting_entity, requester_name, request_type, received_date, requested_deadline, strategic_importance, executive_sponsorship, regulatory_importance, public_impact, dependency_impact, urgency_score, priority_score, priority_level, estimated_effort_hours, complexity, status, created_by) values
  ('044aef90-7716-4ce4-a6d5-e52752b2b733', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0001', 'Healthcare Sector Strategy Review', 'Requested by Ministry of Economy and Planning to support strategy study objectives.', 'Ministry of Economy and Planning', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-07-03', '2026-09-25', 95, 90, 10, 80, 50, 55, 65.75, 'medium', 620, 'high', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('656e8702-85e1-4d25-a085-dfd8cfceb8b7', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0002', 'International Benchmarking Study — Public Transport', 'Requested by Ministry of Health to support benchmarking objectives.', 'Ministry of Health', 'Eng. Mona Al-Tamimi', 'Benchmarking', '2026-08-21', '2026-10-19', 50, 10, 10, 50, 10, 35, 31.50, 'low', 340, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('414e5814-256a-48f5-801c-40de9056444b', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0003', 'Government Operating Model Review', 'Requested by Ministry of Transport to support operating model objectives.', 'Ministry of Transport', 'Dr. Bassam Al-Otaibi', 'Operating Model', '2026-06-28', '2026-11-03', 95, 90, 10, 50, 90, 35, 58.75, 'medium', 780, 'very_high', 'allocated', '22222222-2222-2222-2222-222222222202'),
  ('e539060c-fa06-4741-93dd-b74d6cd904d3', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0004', 'Economic Impact Assessment — Free Zones', 'Requested by Ministry of Communications and IT to support economic study objectives.', 'Ministry of Communications and IT', 'Dr. Bassam Al-Otaibi', 'Economic Study', '2026-08-08', '2026-09-14', 75, 90, 90, 50, 50, 90, 80.25, 'high', 410, 'high', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('fc93ec77-bd69-4508-a606-bab1c01e84ef', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0005', 'Executive Dashboard Development', 'Requested by National Center for Government Excellence to support data & analytics objectives.', 'National Center for Government Excellence', 'Dr. Fahad Al-Ruwaili', 'Data & Analytics', '2026-08-21', '2026-09-18', 50, 90, 10, 20, 10, 75, 52.50, 'medium', 220, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('4289ceef-5dbd-4aa0-995d-51d1217d95d0', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0006', 'Policy Evaluation — Labor Market Reform', 'Requested by Ministry of Labor and Social Development to support policy study objectives.', 'Ministry of Labor and Social Development', 'Dr. Bassam Al-Otaibi', 'Policy Study', '2026-07-12', '2026-08-31', 75, 10, 90, 80, 50, 100, 74.25, 'high', 360, 'high', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('90394544-2251-4616-8cc7-233c4cab6fc6', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0007', 'Service Transformation Assessment — Citizen Services', 'Requested by Ministry of Finance to support transformation objectives.', 'Ministry of Finance', 'Ms. Areej Al-Harbi', 'Transformation', '2026-08-16', '2026-10-04', 75, 90, 10, 80, 50, 55, 60.75, 'medium', 480, 'high', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('36d0cae7-6a27-41d1-93df-b2603d61d615', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0008', 'Digital Maturity Review', 'Requested by Ministry of Investment to support digital transformation objectives.', 'Ministry of Investment', 'Ms. Areej Al-Harbi', 'Digital Transformation', '2026-07-11', '2026-10-24', 50, 10, 10, 20, 10, 35, 28.50, 'low', 260, 'medium', 'submitted', '22222222-2222-2222-2222-222222222202'),
  ('905aa893-13af-41d9-9c80-fc7eb682cd52', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0009', 'Strategic KPI Framework Design', 'Requested by Capital Municipality to support strategy study objectives.', 'Capital Municipality', 'Ms. Areej Al-Harbi', 'Strategy Study', '2026-08-21', '2026-09-29', 75, 90, 10, 50, 50, 55, 57.75, 'medium', 300, 'medium', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('6794cc11-0383-4b92-9f70-9654873a6796', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0010', 'Resource Optimization Study', 'Requested by Digital Government Authority to support operations objectives.', 'Digital Government Authority', 'Dr. Bassam Al-Otaibi', 'Operations', '2026-08-08', '2026-09-10', 50, 10, 10, 20, 10, 90, 45.00, 'low', 250, 'medium', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('01ac6b0b-39ab-47be-b685-36545a227bec', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0011', 'National Data Strategy Alignment', 'Requested by Ministry of Economy and Planning to support strategy study objectives.', 'Ministry of Economy and Planning', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-07-30', '2026-11-13', 95, 90, 90, 50, 90, 35, 70.75, 'high', 700, 'very_high', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0012', 'Ministerial Change Management Program', 'Requested by Ministry of Health to support change management objectives.', 'Ministry of Health', 'Dr. Fahad Al-Ruwaili', 'Change Management', '2026-08-05', '2026-10-14', 75, 90, 10, 50, 50, 55, 57.75, 'medium', 390, 'high', 'allocated', '22222222-2222-2222-2222-222222222202'),
  ('aa28675c-0bf7-4b4d-92b6-7da63b36265b', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0013', 'Regulatory Impact Study — Fintech', 'Requested by Ministry of Transport to support policy study objectives.', 'Ministry of Transport', 'Dr. Bassam Al-Otaibi', 'Policy Study', '2026-06-23', '2026-09-16', 75, 10, 90, 50, 50, 75, 63.75, 'medium', 320, 'high', 'under_review', '22222222-2222-2222-2222-222222222202'),
  ('ccfbbedb-0529-43f6-a880-fe1452aab560', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0014', 'Stakeholder Engagement Framework', 'Requested by Ministry of Communications and IT to support strategy study objectives.', 'Ministry of Communications and IT', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-08-09', '2026-10-09', 50, 10, 10, 20, 10, 55, 34.50, 'low', 150, 'low', 'submitted', '22222222-2222-2222-2222-222222222202'),
  ('e255c0b4-7a15-475b-8de0-d19076487be7', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0015', 'Program Governance Health Check', 'Requested by National Center for Government Excellence to support program management objectives.', 'National Center for Government Excellence', 'Dr. Fahad Al-Ruwaili', 'Program Management', '2026-07-04', '2026-09-06', 50, 10, 10, 20, 50, 100, 50.00, 'medium', 180, 'medium', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('d19b5b40-3ba9-4764-87dc-79667f91d441', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0016', 'Public-Private Partnership Feasibility Study', 'Requested by Ministry of Labor and Social Development to support economic study objectives.', 'Ministry of Labor and Social Development', 'Dr. Fahad Al-Ruwaili', 'Economic Study', '2026-06-27', '2026-10-29', 75, 90, 90, 50, 90, 35, 65.75, 'medium', 640, 'very_high', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0017', 'Workforce Planning Model Update', 'Requested by Ministry of Finance to support operations objectives.', 'Ministry of Finance', 'Eng. Mona Al-Tamimi', 'Operations', '2026-06-25', '2026-11-23', 20, 10, 10, 20, 10, 35, 21.00, 'low', 120, 'low', 'draft', '22222222-2222-2222-2222-222222222202'),
  ('cd99783e-7d3d-404e-bbdf-29c1c26fe377', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0018', 'Sector Competitiveness Benchmark', 'Requested by Ministry of Investment to support benchmarking objectives.', 'Ministry of Investment', 'Dr. Bassam Al-Otaibi', 'Benchmarking', '2026-07-06', '2026-09-22', 50, 10, 10, 50, 10, 75, 43.50, 'low', 280, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202')
on conflict do nothing;

-- Request skills -------------------------------------------------------------
insert into public.request_skills (id, organization_id, request_id, skill_id, required_level, importance_weight, mandatory) values
  ('631305b5-a768-4ed3-9ac6-34ad84465ae3', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'e184b40f-dd92-496f-8c9b-0ad2db1af908', 4, 1.5, true),
  ('50a5e229-b0fe-47d5-854a-6a2dcb0f9ca6', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 3, 1, true),
  ('29185442-0e16-4ff0-8f24-b666a69be8b7', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, false),
  ('b1e4211a-6dc3-4c2b-a5a6-334d613240ef', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 1, false),
  ('ef8b173c-3d67-4b00-9906-e51fc762b043', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 4, 1.5, true),
  ('8032dac5-d546-460c-b9bf-a9bd3cb98654', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 1, true),
  ('5262f889-79f4-48a5-9027-8e1369c76add', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', '3ba88147-244b-4191-b657-fa1af6c87123', 3, 1, false),
  ('50ca986a-652b-4ed9-8623-7fded81d9793', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', '17e53c86-ac3d-4f96-9d0a-4e182593cc43', 4, 1.5, true),
  ('23dfc076-511a-4a08-a182-782a60abaffd', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 3, 1, true),
  ('a5c2ccb9-7a57-4a97-bb70-8d9adfbd4cc8', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 3, 1, false),
  ('8a6b7f96-c11e-47c8-a037-a8eba208b286', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 4, 1.5, true),
  ('b507b2f6-977f-4805-be5f-3f8e9d88d542', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 3, 1, true),
  ('bdbedadb-5c17-485e-bfc8-7d06108af49a', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', '44171332-a5ec-481a-88a4-1a0e733a7e24', 3, 1, false),
  ('19d47343-30b7-409c-9e77-0e55166faccc', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 4, 1.5, true),
  ('9ee7183a-4434-463c-bd68-31a7b4e17aa8', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', 'f903f9e9-b47f-4d60-923f-13a80f4b397f', 3, 1, true),
  ('2347a06a-4b89-4945-8df9-632a63949b1f', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 3, 1, false),
  ('031b9c9c-8494-4081-a823-f9bf83caa638', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', 4, 1.5, true),
  ('82dd9261-0f74-4597-96c0-a569bef2ab44', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 1, true),
  ('9d1c5267-e1d5-48e6-b3b2-af2c6e341374', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, false),
  ('d789719a-0f14-4eb9-9a7b-5e82191844fc', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 4, 1.5, true),
  ('f3119772-c64c-43c1-8ce1-55b1d7730a40', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', '34f8461d-6e0b-46a3-9fe9-297d3f063e08', 3, 1, true),
  ('60d422b2-87a9-4b2f-b358-defb73b5ebd1', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 3, 1, false),
  ('5b975479-d839-4d44-be3a-b044bd72966d', '11111111-1111-1111-1111-111111111111', '36d0cae7-6a27-41d1-93df-b2603d61d615', '3e0cb5f4-ea6f-4a87-8bb7-197a4a2804f1', 4, 1.5, true),
  ('60ddbced-4703-416e-babb-8edec5be1558', '11111111-1111-1111-1111-111111111111', '36d0cae7-6a27-41d1-93df-b2603d61d615', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 3, 1, true),
  ('f4170cc4-5768-4be2-adab-b0b31824032c', '11111111-1111-1111-1111-111111111111', '36d0cae7-6a27-41d1-93df-b2603d61d615', '40feffce-fd89-40d6-85ee-eb84b8861b7d', 3, 1, false),
  ('fcd66423-4d86-41d9-a056-692c60fd2394', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 4, 1.5, true),
  ('2bc65981-cdf9-400b-ba95-389f7c08a5a8', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, true),
  ('ad616b99-f305-4697-aa85-4767eba0e216', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 1, false),
  ('7a8c3261-6f19-4bca-a79b-8a8787500310', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 4, 1.5, true),
  ('875e0933-eb09-4082-86c6-51fe5ffc8fcf', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', '819a7096-33d1-4415-a83c-8d5132abf13f', 3, 1, true),
  ('f1351c8c-ae06-42a2-8b3a-c90dbda7a256', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 3, 1, false),
  ('c3c9203e-263c-4bb6-b0d8-fdfe01c919db', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 4, 1.5, true),
  ('57852a43-668d-4e19-92cd-2bcb6f728c18', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, true),
  ('eec04e65-7cef-4c1c-b58c-76ac54d7f0ae', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 1, false),
  ('2c37e891-519a-4c0d-add1-3100297d18a6', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', '34f8461d-6e0b-46a3-9fe9-297d3f063e08', 4, 1.5, true),
  ('c2db10d0-8695-45e8-956c-0358e58bd2c5', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, true),
  ('c44203d4-d448-4f43-bbdc-96ba1f15725f', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 1, false),
  ('8b116530-414f-4364-ad62-1537e0b69cd5', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'f5d7f1fe-f45f-4b4d-acad-71d57e9f6700', 4, 1.5, true),
  ('a32c867a-5cc7-45a4-ad22-8a6b5cf8a798', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 1, true),
  ('34191df1-a691-4038-af15-c972486974a6', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, false),
  ('c4216e31-9d76-43aa-a6ca-6281ca89efe2', '11111111-1111-1111-1111-111111111111', 'ccfbbedb-0529-43f6-a880-fe1452aab560', '252d4d1f-8474-4a5e-8c92-5a96b15e93ab', 4, 1.5, true),
  ('423b90ca-652f-4147-bbd4-caddca6d7ab0', '11111111-1111-1111-1111-111111111111', 'ccfbbedb-0529-43f6-a880-fe1452aab560', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, true),
  ('f20f70a1-a286-439c-b971-f72460c73ded', '11111111-1111-1111-1111-111111111111', 'ccfbbedb-0529-43f6-a880-fe1452aab560', '1bcea6cc-b723-4fc9-b0ac-b33d20161629', 3, 1, false),
  ('eb36decf-e9c0-4556-b481-1fe92d8ce21a', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', '2e84c1c3-8700-473e-849e-f0a87d0e0cbe', 4, 1.5, true),
  ('44ea62ea-b2cd-46c1-b128-661464258de1', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', '819a7096-33d1-4415-a83c-8d5132abf13f', 3, 1, true),
  ('53ff26f9-4303-4851-99cf-1f3c2ead5ef4', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', 'e7cf5519-564e-4a1e-96a7-aa2d8f845c78', 3, 1, false),
  ('3c70d6c8-b892-425d-b097-5ac2fef3b8a9', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', 'fb99e48d-f99b-4212-8576-fa730dfafbec', 4, 1.5, true),
  ('412b7f59-e1b7-4464-b1c3-97520e794a54', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', '0da732b5-e1b8-4e36-8144-37c8bf5bb333', 3, 1, true),
  ('0d28b5af-4b6f-47d1-9ee6-e0ae43337102', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', '44171332-a5ec-481a-88a4-1a0e733a7e24', 3, 1, false),
  ('caddfae5-5186-4df1-8247-3027d7c80bf1', '11111111-1111-1111-1111-111111111111', '18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', 'b2b54461-576d-47d0-a2d6-b4d673ddef0e', 4, 1.5, true),
  ('cc4aa3a3-da65-4b96-9455-579e006a046a', '11111111-1111-1111-1111-111111111111', '18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', '819a7096-33d1-4415-a83c-8d5132abf13f', 3, 1, true),
  ('90215572-6f72-4985-89b3-17a7151958a6', '11111111-1111-1111-1111-111111111111', '18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', '8eee5b95-3303-4b45-969b-78d2ffe7e837', 3, 1, false),
  ('a92d6e02-5e0c-4a3b-8d52-ad8d45d13d0a', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', '2d91a0cd-2cae-42b2-9be5-381d61a0cff0', 4, 1.5, true),
  ('4aea0b26-b673-4237-884c-3144ba91102b', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', 'b2c8de97-520b-4f49-8a07-c2045257a0b3', 3, 1, true),
  ('eb56ace8-1f5e-4919-b2f1-e263bfbad42a', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', '3ba88147-244b-4191-b657-fa1af6c87123', 3, 1, false)
on conflict do nothing;

-- Deliverables -----------------------------------------------------------------
insert into public.deliverables (id, organization_id, request_id, title, due_date, estimated_hours, status) values
  ('c3d2c823-ac7c-4a45-9d38-2da94c8e803f', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'Healthcare Sector Strategy Review — Diagnostic Report', '2026-09-11', 186, 'in_progress'),
  ('383a3b8f-bf96-40f2-97b9-58cf136c48ca', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'Healthcare Sector Strategy Review — Final Recommendations', '2026-09-25', 248, 'not_started'),
  ('477cb9d3-0871-4763-a7b6-cecb4f6bbd4c', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', 'International Benchmarking Study — Public Transport — Diagnostic Report', '2026-10-05', 102, 'in_progress'),
  ('75df57c4-89a6-470f-a279-665a2e825985', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', 'International Benchmarking Study — Public Transport — Final Recommendations', '2026-10-19', 136, 'not_started'),
  ('ffdd6749-5dd2-482d-9cbd-f0cba3cb0b86', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'Government Operating Model Review — Diagnostic Report', '2026-10-20', 234, 'in_progress'),
  ('93e1dec8-461f-43ba-bced-1009efcd570a', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'Government Operating Model Review — Final Recommendations', '2026-11-03', 312, 'not_started'),
  ('0cc53292-e252-49ce-839d-9e496e8eeeb4', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', 'Economic Impact Assessment — Free Zones — Diagnostic Report', '2026-08-31', 123, 'in_progress'),
  ('407ca0f4-7522-4680-ac41-816d340be1fe', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', 'Economic Impact Assessment — Free Zones — Final Recommendations', '2026-09-14', 164, 'not_started'),
  ('3d43da62-54a7-4816-89c3-be3971edf206', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', 'Executive Dashboard Development — Diagnostic Report', '2026-09-04', 66, 'in_progress'),
  ('88123910-cd14-4e42-a218-de501771de3b', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', 'Executive Dashboard Development — Final Recommendations', '2026-09-18', 88, 'not_started'),
  ('931423df-dd8d-4e91-9222-ec247d7c7d34', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'Policy Evaluation — Labor Market Reform — Diagnostic Report', '2026-08-17', 108, 'in_progress'),
  ('672c9663-4aab-4f0c-8c50-fe7787f6b1b0', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'Policy Evaluation — Labor Market Reform — Final Recommendations', '2026-08-31', 144, 'not_started'),
  ('4af8f709-2fba-444c-ad50-39393bb1de21', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'Service Transformation Assessment — Citizen Services — Diagnostic Report', '2026-09-20', 144, 'in_progress'),
  ('19e5c4f8-4a2c-4dba-b2d5-511e49920a68', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'Service Transformation Assessment — Citizen Services — Final Recommendations', '2026-10-04', 192, 'not_started'),
  ('389725d9-ac67-4b26-9757-a3f57074ab7f', '11111111-1111-1111-1111-111111111111', '36d0cae7-6a27-41d1-93df-b2603d61d615', 'Digital Maturity Review — Diagnostic Report', '2026-10-10', 78, 'in_progress'),
  ('f8bd2e68-f6ea-4a10-8a74-c03c48871a0a', '11111111-1111-1111-1111-111111111111', '36d0cae7-6a27-41d1-93df-b2603d61d615', 'Digital Maturity Review — Final Recommendations', '2026-10-24', 104, 'not_started'),
  ('b0ad33a1-b629-439e-abde-dded5a15d218', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', 'Strategic KPI Framework Design — Diagnostic Report', '2026-09-15', 90, 'in_progress'),
  ('10e71349-19f6-4c11-a711-4fd23ae7e800', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', 'Strategic KPI Framework Design — Final Recommendations', '2026-09-29', 120, 'not_started'),
  ('dbd4b083-21b3-4624-9923-07866cbc2112', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', 'Resource Optimization Study — Diagnostic Report', '2026-08-27', 75, 'in_progress'),
  ('c10f70bd-3a64-4493-a366-adcab122aa5f', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', 'Resource Optimization Study — Final Recommendations', '2026-09-10', 100, 'not_started'),
  ('9c18998b-d30e-4612-9806-8b9a1ca1bfdf', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'National Data Strategy Alignment — Diagnostic Report', '2026-10-30', 210, 'in_progress'),
  ('3d9370b8-0af0-4d4c-8593-47c2e327d77d', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'National Data Strategy Alignment — Final Recommendations', '2026-11-13', 280, 'not_started'),
  ('7c281464-bf18-4515-887e-dc4eed32f67c', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', 'Ministerial Change Management Program — Diagnostic Report', '2026-09-30', 117, 'in_progress'),
  ('133ad4a8-3b58-4b65-bd86-637a483bd96e', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', 'Ministerial Change Management Program — Final Recommendations', '2026-10-14', 156, 'not_started'),
  ('84085eae-ee11-4683-8a41-add65b88cab4', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'Regulatory Impact Study — Fintech — Diagnostic Report', '2026-09-02', 96, 'in_progress'),
  ('bdc2c62d-0bd0-4f51-a8b4-692f796537a9', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'Regulatory Impact Study — Fintech — Final Recommendations', '2026-09-16', 128, 'not_started'),
  ('349d22e4-419a-4a3a-bae5-f79245bf7426', '11111111-1111-1111-1111-111111111111', 'ccfbbedb-0529-43f6-a880-fe1452aab560', 'Stakeholder Engagement Framework — Diagnostic Report', '2026-09-25', 45, 'in_progress'),
  ('ea808939-c895-4ab8-8049-faad14a5f36a', '11111111-1111-1111-1111-111111111111', 'ccfbbedb-0529-43f6-a880-fe1452aab560', 'Stakeholder Engagement Framework — Final Recommendations', '2026-10-09', 60, 'not_started'),
  ('50b7e2aa-ed39-4ee2-a232-749881c98c97', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', 'Program Governance Health Check — Diagnostic Report', '2026-08-23', 54, 'in_progress'),
  ('1d3eac75-a077-4dca-a84f-889c01ea4b1d', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', 'Program Governance Health Check — Final Recommendations', '2026-09-06', 72, 'not_started'),
  ('e5e3da16-2382-4b8e-9490-eedd1799d7fc', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', 'Public-Private Partnership Feasibility Study — Diagnostic Report', '2026-10-15', 192, 'in_progress'),
  ('340442c7-9594-4c80-a087-07bb2c5e47ea', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', 'Public-Private Partnership Feasibility Study — Final Recommendations', '2026-10-29', 256, 'not_started'),
  ('999493f1-fe7a-4dd4-abe6-95f95ce5994c', '11111111-1111-1111-1111-111111111111', '18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', 'Workforce Planning Model Update — Diagnostic Report', '2026-11-09', 36, 'not_started'),
  ('7f712d1b-67bd-425d-b127-f17e24b348fe', '11111111-1111-1111-1111-111111111111', '18661aa8-7ca3-4ef3-8ac4-b42fe6c80aeb', 'Workforce Planning Model Update — Final Recommendations', '2026-11-23', 48, 'not_started'),
  ('1436e26b-c3c2-44aa-bb36-dc9b1425466f', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', 'Sector Competitiveness Benchmark — Diagnostic Report', '2026-09-08', 84, 'in_progress'),
  ('792dfa12-13f0-4e7a-89fa-cb1dbf9f429c', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', 'Sector Competitiveness Benchmark — Final Recommendations', '2026-09-22', 112, 'not_started')
on conflict do nothing;

-- Assignments ----------------------------------------------------------------
insert into public.assignments (id, organization_id, request_id, resource_id, assignment_role, allocation_percentage, allocated_hours, start_date, end_date, status, approved_by, approved_at) values
  ('b0a0aee8-921c-460f-9954-da601c35b941', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'lead', 60, 216, '2026-08-25', '2026-10-24', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('6740eced-5669-401d-a06f-a179f8b52310', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'contributor', 45, 108, '2026-08-30', '2026-10-14', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a20c3b6a-7bb5-42cb-adf1-ceae4b041800', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'contributor', 20, 32, '2026-09-04', '2026-10-04', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('4e717256-18fd-4138-8c2b-bf02a80bc058', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', 'c2587a96-3099-4978-98c0-61181d242fe3', 'lead', 60, 216, '2026-08-25', '2026-10-24', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('5c36a532-0006-4856-b355-b27e4af91545', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'c2587a96-3099-4978-98c0-61181d242fe3', 'contributor', 45, 108, '2026-08-30', '2026-10-14', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('f19ac735-e562-4817-92b2-3dc5bf7dfdea', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'lead', 60, 216, '2026-08-25', '2026-10-24', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('5529f868-c151-4839-b72b-630e4e48c1fa', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'contributor', 45, 108, '2026-08-30', '2026-10-14', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('dbeabb45-5fbc-4c3b-88fb-e2bf301da1b4', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf', 'contributor', 20, 32, '2026-09-04', '2026-10-04', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('4c66bb8c-b6c0-4177-aa27-308725645c60', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'ace286c0-7345-40a7-9c5c-67effd1a4b0f', 'lead', 40, 96, '2026-08-28', '2026-10-07', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('44e86101-083d-4f8c-bf90-7df89e642a43', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', '02c3dea2-553e-4ad0-a0b3-56fa8003c493', 'contributor', 50, 140, '2026-08-29', '2026-10-18', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a7ea15c6-872f-4495-81e2-990e07d59493', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'fee798aa-d69d-49f7-9b9d-d62d9b62402c', 'contributor', 60, 216, '2026-08-30', '2026-10-29', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('8c4c0046-5cc8-449b-8b84-4575c76699be', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', 'd5c31e44-a16b-4690-92bf-92df9a691efe', 'lead', 70, 168, '2026-08-31', '2026-10-10', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('f8ea119c-fe09-4c70-9aa6-220f4fff3de6', '11111111-1111-1111-1111-111111111111', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'contributor', 40, 112, '2026-09-01', '2026-10-21', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('fffcf682-c514-41de-82dd-89851bfba65c', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', '34ab6168-47b3-48d2-b9f3-8ff5e7962c8d', 'contributor', 50, 180, '2026-08-28', '2026-10-27', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('f0d55b0a-d07c-40a0-879e-2484d33b7a38', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'c6f87582-3e5f-4d56-852d-759122e4b91b', 'lead', 60, 144, '2026-08-29', '2026-10-08', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('df4e72a2-2d88-4cdf-804d-13d23ee703ab', '11111111-1111-1111-1111-111111111111', '905aa893-13af-41d9-9c80-fc7eb682cd52', 'b8b5ad0f-8cff-49cb-8e53-9732fa0ac7a6', 'contributor', 70, 196, '2026-08-30', '2026-10-19', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('fa9f239a-158c-4fb9-a70b-5c2d379f71c7', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', 'a8bc2041-f849-403e-b7ee-3bba019125ff', 'contributor', 40, 144, '2026-08-31', '2026-10-30', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('e099d707-a889-4f7a-9fb1-97b73a6c12d6', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'f4accce0-288f-42a0-8091-c6328ed617fc', 'lead', 50, 120, '2026-09-01', '2026-10-11', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a362c5dc-5cf5-4517-b369-7b2e25b60c59', '11111111-1111-1111-1111-111111111111', 'fd66373e-d3cd-4ad2-91b3-37bcc1de4bc0', 'e80df80d-f636-4458-8ed9-e8674e555db3', 'contributor', 60, 168, '2026-08-28', '2026-10-17', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('38481e96-69bc-4556-ac34-fd8193c33fa4', '11111111-1111-1111-1111-111111111111', 'aa28675c-0bf7-4b4d-92b6-7da63b36265b', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'contributor', 70, 252, '2026-08-29', '2026-10-28', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('2ee2b314-db97-4c36-b938-8cedfc88dcea', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', 'a17e59bf-7d9e-4c22-9eb4-8e88bf4158d0', 'lead', 40, 77, '2026-08-30', '2026-10-09', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('b9361939-6d7c-40ea-a770-0718c4c0ea86', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', 'a663ae9f-8faa-448a-bfaf-da2d142d5988', 'contributor', 50, 140, '2026-08-31', '2026-10-20', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('79270868-8fa6-4c69-860a-516d22446b71', '11111111-1111-1111-1111-111111111111', 'cd99783e-7d3d-404e-bbdf-29c1c26fe377', 'be7576fd-7580-462c-9409-8f0712f73b8c', 'contributor', 60, 216, '2026-09-01', '2026-10-31', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a45eab7b-2140-4429-a121-722863c3a136', '11111111-1111-1111-1111-111111111111', '044aef90-7716-4ce4-a6d5-e52752b2b733', 'a0d0e5c2-0712-4640-8adf-23943c987cc7', 'lead', 70, 168, '2026-08-28', '2026-10-07', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('1fd085fe-92fa-4c1e-b87a-5c15bb86dc6a', '11111111-1111-1111-1111-111111111111', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', 'f7215d4d-ef59-417b-a156-1435ea1d215a', 'contributor', 40, 112, '2026-08-29', '2026-10-18', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('31f03dd3-f7c8-44a6-82bb-519f39cd54e1', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'bb38b2b2-7489-42b3-9728-f79cd087b758', 'contributor', 15, 18, '2026-09-02', '2026-09-22', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('830610e0-1583-49c1-ab4e-6a37d316b36b', '11111111-1111-1111-1111-111111111111', 'd19b5b40-3ba9-4764-87dc-79667f91d441', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c', 'contributor', 25, 40, '2026-09-01', '2026-09-26', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('1e45ecf8-096f-4fff-91b3-823119fc931d', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'd03e82e3-8224-4c2b-bbb2-af1b60f59943', 'contributor', 27, 43, '2026-09-01', '2026-09-26', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a4bf4af6-3bb2-46da-a44a-6c8736bedba9', '11111111-1111-1111-1111-111111111111', '90394544-2251-4616-8cc7-233c4cab6fc6', 'd85ddb48-74d7-4223-a555-ec8ccb5cd9d8', 'contributor', 16, 26, '2026-09-01', '2026-09-26', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('e59c342a-f0eb-450f-991b-2f4314989e21', '11111111-1111-1111-1111-111111111111', '414e5814-256a-48f5-801c-40de9056444b', 'bb38b2b2-7489-42b3-9728-f79cd087b758', 'contributor', 18, 29, '2026-09-01', '2026-09-26', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('f853c359-62e6-4f66-9c8c-d7da4625dfa9', '11111111-1111-1111-1111-111111111111', '01ac6b0b-39ab-47be-b685-36545a227bec', 'c6313b1a-4c1a-439a-85ab-6abf34799ab6', 'contributor', 23, 37, '2026-09-01', '2026-09-26', 'active', '22222222-2222-2222-2222-222222222202', now())
on conflict do nothing;

-- Risks -------------------------------------------------------------------------
insert into public.risks (id, organization_id, request_id, risk_type, risk_score, severity, description, active) values
  ('5274c0b7-491d-49f4-81a9-2a7363bfda99', '11111111-1111-1111-1111-111111111111', 'e539060c-fa06-4741-93dd-b74d6cd904d3', 'deadline', 77, 'critical', 'Remaining working days are insufficient for the outstanding scope at the current pace.', true),
  ('8196231a-9e26-44cd-aad0-b48fc8d46fb0', '11111111-1111-1111-1111-111111111111', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', 'capacity', 77, 'high', 'Assigned team is projected to exceed sustainable utilization before the deadline.', true),
  ('d9765b9c-9e4a-483a-983b-d364e978261d', '11111111-1111-1111-1111-111111111111', '6794cc11-0383-4b92-9f70-9654873a6796', 'skill_gap', 75, 'critical', 'One or more mandatory skills are only partially covered by the current team.', true),
  ('eeaba1f7-e7eb-4065-ab91-a38e3781da63', '11111111-1111-1111-1111-111111111111', 'e255c0b4-7a15-475b-8de0-d19076487be7', 'dependency', 77, 'high', 'Deliverable depends on inputs from another in-flight engagement that is itself at risk.', true)
on conflict do nothing;

-- Notifications -------------------------------------------------------------------
insert into public.notifications (id, organization_id, user_id, notification_type, severity, title, message, entity_type, entity_id) values
  ('dcb7d1a0-3c47-4015-ae5d-5cc19eb40e7d', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Abdullah Al-Harbi is overloaded', 'Abdullah Al-Harbi is projected above the organization overload threshold based on current assignments.', 'resource', 'd4d6a4da-36e3-44c3-ab59-cfc37b923c5c'),
  ('ea53d854-7622-4fb7-9948-ee37d23a79ec', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Ahmed Al-Amri is overloaded', 'Ahmed Al-Amri is projected above the organization overload threshold based on current assignments.', 'resource', 'c2587a96-3099-4978-98c0-61181d242fe3'),
  ('0d3dc612-8fac-4c21-ab5f-e0c0308d8e70', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Majed Al-Shehri is overloaded', 'Majed Al-Shehri is projected above the organization overload threshold based on current assignments.', 'resource', 'a5b9eb0d-31b6-404d-bb73-bd0bbefd6dcf'),
  ('91e4888f-7e3d-4744-9ef5-b427212a9bb8', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Economic Impact Assessment — Free Zones delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', 'e539060c-fa06-4741-93dd-b74d6cd904d3'),
  ('fd424ffc-1cb0-4d63-ac8d-c56054588d85', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Policy Evaluation — Labor Market Reform delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', '4289ceef-5dbd-4aa0-995d-51d1217d95d0'),
  ('45c250a9-0c11-48e8-b2ed-659fd0c0ef00', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Resource Optimization Study delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', '6794cc11-0383-4b92-9f70-9654873a6796'),
  ('918e69dc-d280-4e80-ae66-fdfdbf60bb70', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Program Governance Health Check delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', 'e255c0b4-7a15-475b-8de0-d19076487be7')
on conflict do nothing;

-- Audit trail ----------------------------------------------------------------------
insert into public.audit_logs (id, organization_id, user_id, action, entity_type, entity_id, old_value, new_value, reason) values
  ('51a424d5-65b6-4e55-b8dd-336bf2e1393d', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '044aef90-7716-4ce4-a6d5-e52752b2b733', null, '{"status":"draft","title":"Healthcare Sector Strategy Review"}'::jsonb, null),
  ('e8fe7e5d-2b66-4c2f-8901-bd707a049fe6', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '656e8702-85e1-4d25-a085-dfd8cfceb8b7', null, '{"status":"draft","title":"International Benchmarking Study — Public Transport"}'::jsonb, null),
  ('4f94fe0a-2fc8-4be4-8b94-1cbe1708dbcd', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '414e5814-256a-48f5-801c-40de9056444b', null, '{"status":"draft","title":"Government Operating Model Review"}'::jsonb, null),
  ('531945d4-0d2d-472b-bedc-39d89c4c4d4a', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', 'e539060c-fa06-4741-93dd-b74d6cd904d3', null, '{"status":"draft","title":"Economic Impact Assessment — Free Zones"}'::jsonb, null),
  ('5eaad6b1-0bf0-4856-8cc9-e4fdbef5e30f', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', 'fc93ec77-bd69-4508-a606-bab1c01e84ef', null, '{"status":"draft","title":"Executive Dashboard Development"}'::jsonb, null),
  ('2a9cf701-b33d-4840-89f9-cb1e8020a56f', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '4289ceef-5dbd-4aa0-995d-51d1217d95d0', null, '{"status":"draft","title":"Policy Evaluation — Labor Market Reform"}'::jsonb, null),
  ('5be5e5a4-42e9-4998-8d4c-1c6165ab904b', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', 'b0a0aee8-921c-460f-9954-da601c35b941', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('d18c69f1-a200-4b6d-b951-2b0fa27ee48c', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '6740eced-5669-401d-a06f-a179f8b52310', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('c22d2539-c377-491b-ae36-91bc6ab8d2bf', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', 'a20c3b6a-7bb5-42cb-adf1-ceae4b041800', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":20}'::jsonb, 'management_decision'),
  ('7fb1ab8b-26db-40eb-b4d9-442db2d0ff23', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '4e717256-18fd-4138-8c2b-bf02a80bc058', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('a3233aba-8bbf-4f37-a707-aa71770954ef', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '5c36a532-0006-4856-b355-b27e4af91545', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('676ec9fe-583f-4389-ba6e-960d6c583437', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', 'f19ac735-e562-4817-92b2-3dc5bf7dfdea', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('da5e1625-7544-4d81-a8d0-568fb4060a87', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '5529f868-c151-4839-b72b-630e4e48c1fa', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('5f81a892-6768-4226-99dd-4ee7e61a310b', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', 'dbeabb45-5fbc-4c3b-88fb-e2bf301da1b4', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":20}'::jsonb, 'management_decision')
on conflict do nothing;

commit;
