-- RA Copilot demo seed: Government Advisory Center
-- Generated by scripts/generate-seed.mjs — do not hand-edit, regenerate instead.
begin;

-- Organization --------------------------------------------------------
insert into public.organizations (id, name, name_ar, timezone, working_days, daily_work_hours, weekly_work_hours, target_utilization, overload_threshold)
values ('11111111-1111-1111-1111-111111111111', 'Government Advisory Center', 'مركز الاستشارات الحكومية', 'Asia/Riyadh', '[0,1,2,3,4]'::jsonb, 8, 40, 0.85, 0.90)
on conflict (id) do nothing;

-- Demo accounts (auth.users -> profiles is auto-provisioned by trigger) ------
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222201', 'authenticated', 'authenticated', 'admin@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Layla Al-Fahad","role":"admin","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222201', '22222222-2222-2222-2222-222222222201', '{"sub":"22222222-2222-2222-2222-222222222201","email":"admin@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222202', 'authenticated', 'authenticated', 'manager@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Abdulaziz Al-Nasser","role":"resource_manager","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222202', '22222222-2222-2222-2222-222222222202', '{"sub":"22222222-2222-2222-2222-222222222202","email":"manager@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222203', 'authenticated', 'authenticated', 'consultant@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Sara Al-Mutairi","role":"consultant","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222203', '22222222-2222-2222-2222-222222222203', '{"sub":"22222222-2222-2222-2222-222222222203","email":"consultant@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222204', 'authenticated', 'authenticated', 'executive@racopilot.demo',
  crypt('RaCopilot!Demo1', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Turki Al-Saud","role":"executive_viewer","organization_id":"11111111-1111-1111-1111-111111111111"}'::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '22222222-2222-2222-2222-222222222204', '22222222-2222-2222-2222-222222222204', '{"sub":"22222222-2222-2222-2222-222222222204","email":"executive@racopilot.demo"}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;

-- link the consultant demo login to its resource record once resources exist
-- (see end of file)

-- Skills ---------------------------------------------------------------
insert into public.skills (id, organization_id, name, category) values
  ('ef35cf3f-7f0c-457b-8e94-fad8180e5665', '11111111-1111-1111-1111-111111111111', 'Strategy', 'Strategy'),
  ('00431c02-9264-48b6-a566-434e2930bcfc', '11111111-1111-1111-1111-111111111111', 'Policy', 'Strategy'),
  ('eb514dca-7bbc-4924-a9ba-13d4c84249e7', '11111111-1111-1111-1111-111111111111', 'Research', 'Analysis'),
  ('94cc928e-58bb-44ab-84f5-39d846d7cb47', '11111111-1111-1111-1111-111111111111', 'Benchmarking', 'Analysis'),
  ('33511ddb-d37c-4bd0-9390-224ae2301d6f', '11111111-1111-1111-1111-111111111111', 'Data Analysis', 'Data'),
  ('fe107564-9451-40cc-8419-6b70b075f7ac', '11111111-1111-1111-1111-111111111111', 'Power BI', 'Data'),
  ('5285b115-c057-4efa-981a-982d21df9fa6', '11111111-1111-1111-1111-111111111111', 'Financial Modeling', 'Finance'),
  ('1483e1a5-356f-482f-8ce4-ef8e061e5427', '11111111-1111-1111-1111-111111111111', 'Economics', 'Finance'),
  ('17e54823-8ecb-451e-9672-981659219b83', '11111111-1111-1111-1111-111111111111', 'Healthcare', 'Sector'),
  ('84aad79c-80e5-49b0-94e3-8b6c5c51159e', '11111111-1111-1111-1111-111111111111', 'Digital Transformation', 'Strategy'),
  ('5be9b3b2-f502-4193-8ce2-d887c6e4f7de', '11111111-1111-1111-1111-111111111111', 'Operating Model', 'Strategy'),
  ('8afcef81-f811-417d-bb65-25033e2bd3c2', '11111111-1111-1111-1111-111111111111', 'Process Improvement', 'Operations'),
  ('4af12cdd-f67c-4411-b499-77defa8cc6b2', '11111111-1111-1111-1111-111111111111', 'Project Management', 'Delivery'),
  ('14181039-cd7e-4aa5-a970-ef5addc528ac', '11111111-1111-1111-1111-111111111111', 'Program Management', 'Delivery'),
  ('2b47b5f9-41f6-4eea-a36f-486af92ce571', '11111111-1111-1111-1111-111111111111', 'Stakeholder Management', 'Delivery'),
  ('2452a1f9-9e96-48f4-a572-6c5e61e3016c', '11111111-1111-1111-1111-111111111111', 'Presentation', 'Delivery'),
  ('496f21dd-27ca-41eb-be0c-dc1a84a34427', '11111111-1111-1111-1111-111111111111', 'Quantitative Analysis', 'Analysis'),
  ('0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', '11111111-1111-1111-1111-111111111111', 'Market Analysis', 'Analysis'),
  ('1e06f48f-f3b0-4fd5-bca0-579a53fada6f', '11111111-1111-1111-1111-111111111111', 'Business Analysis', 'Analysis'),
  ('4697eeca-7e39-4d4b-b9e4-6b70c5f34585', '11111111-1111-1111-1111-111111111111', 'Change Management', 'Operations')
on conflict do nothing;

-- Resources --------------------------------------------------------------
insert into public.resources (id, organization_id, employee_code, full_name, job_title, department, seniority_level, weekly_capacity_hours, utilization_target, active) values
  ('329bad2e-a232-4a77-8358-aa1350d06e09', '11111111-1111-1111-1111-111111111111', 'GAC-001', 'Sara Al-Mutairi', 'Consultant', 'Strategy & Transformation', 3, 40, 0.85, true),
  ('291e2509-525f-4b4c-b692-e85d58e87baf', '11111111-1111-1111-1111-111111111111', 'GAC-002', 'Abdullah Al-Harbi', 'Senior Consultant', 'Data & Analytics', 4, 40, 0.85, true),
  ('60de1196-ab57-4caf-b9dd-f747edb274d5', '11111111-1111-1111-1111-111111111111', 'GAC-003', 'Noura Al-Qahtani', 'Senior Analyst', 'Policy & Research', 2, 40, 0.85, true),
  ('ce003944-aa2b-47c2-820d-bf2da66afbd2', '11111111-1111-1111-1111-111111111111', 'GAC-004', 'Faisal Al-Otaibi', 'Principal Consultant', 'Economics', 5, 40, 0.85, true),
  ('f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '11111111-1111-1111-1111-111111111111', 'GAC-005', 'Maha Al-Zahrani', 'Consultant', 'Program Management', 3, 40, 0.85, true),
  ('f348c6f9-f853-46c8-b26f-b66526236198', '11111111-1111-1111-1111-111111111111', 'GAC-006', 'Khalid Al-Ghamdi', 'Senior Consultant', 'Sector Advisory', 4, 40, 0.85, true),
  ('89560178-7e10-43ad-a06b-a6d14bee71af', '11111111-1111-1111-1111-111111111111', 'GAC-007', 'Rana Al-Dosari', 'Senior Analyst', 'Strategy & Transformation', 2, 40, 0.85, true),
  ('64cb761a-5fe9-446d-ac33-dffc2278232d', '11111111-1111-1111-1111-111111111111', 'GAC-008', 'Omar Al-Balawi', 'Consultant', 'Data & Analytics', 3, 40, 0.85, true),
  ('1c19ae02-200e-44fa-abf9-0029422e6df2', '11111111-1111-1111-1111-111111111111', 'GAC-009', 'Hind Al-Shammari', 'Senior Analyst', 'Executive Support', 2, 24, 0.85, true),
  ('bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '11111111-1111-1111-1111-111111111111', 'GAC-010', 'Yousef Al-Anazi', 'Consultant', 'Policy & Research', 3, 40, 0.85, true),
  ('6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', '11111111-1111-1111-1111-111111111111', 'GAC-011', 'Ahmed Al-Amri', 'Principal Consultant', 'Sector Advisory', 5, 40, 0.85, true),
  ('cb21478c-9a36-47b7-a918-5ff533152bc5', '11111111-1111-1111-1111-111111111111', 'GAC-012', 'Reem Al-Subaie', 'Senior Analyst', 'Economics', 2, 40, 0.85, true),
  ('2225dfe0-1120-4655-a956-1d2d77622bcf', '11111111-1111-1111-1111-111111111111', 'GAC-013', 'Tariq Al-Qahtani', 'Senior Consultant', 'Program Management', 4, 40, 0.85, true),
  ('1815f820-f21a-4b99-868d-ccfc5290cf96', '11111111-1111-1111-1111-111111111111', 'GAC-014', 'Dana Al-Harthi', 'Consultant', 'Strategy & Transformation', 3, 40, 0.85, true),
  ('6dbf8915-6425-4d5b-902e-aa14822c7092', '11111111-1111-1111-1111-111111111111', 'GAC-015', 'Saud Al-Rashidi', 'Senior Analyst', 'Data & Analytics', 2, 40, 0.85, true),
  ('ee22173c-63d5-47c0-8cf8-cd09853027cc', '11111111-1111-1111-1111-111111111111', 'GAC-016', 'Aisha Al-Malki', 'Senior Consultant', 'Policy & Research', 4, 40, 0.85, true),
  ('96b6cac2-edbf-4db4-99d2-adf0d9abde00', '11111111-1111-1111-1111-111111111111', 'GAC-017', 'Bandar Al-Juhani', 'Consultant', 'Sector Advisory', 3, 40, 0.85, true),
  ('a26e0f86-23d7-4f75-ab41-2c66d49f2410', '11111111-1111-1111-1111-111111111111', 'GAC-018', 'Fatimah Al-Yami', 'Consultant', 'Economics', 3, 32, 0.85, true),
  ('fe210665-1612-4518-988a-230a8936c1eb', '11111111-1111-1111-1111-111111111111', 'GAC-019', 'Nasser Al-Otaibi', 'Senior Analyst', 'Program Management', 2, 40, 0.85, true),
  ('bf9be801-eaa5-4854-a0fe-6d1146343c50', '11111111-1111-1111-1111-111111111111', 'GAC-020', 'Wafa Al-Saleh', 'Consultant', 'Executive Support', 3, 40, 0.85, true),
  ('30e85f72-9270-41d4-8a6e-c02df504f394', '11111111-1111-1111-1111-111111111111', 'GAC-021', 'Majed Al-Shehri', 'Senior Consultant', 'Strategy & Transformation', 4, 40, 0.85, true),
  ('6f87b37c-3af1-462d-9d0d-81ef9e6714a9', '11111111-1111-1111-1111-111111111111', 'GAC-022', 'Amal Al-Qarni', 'Consultant', 'Data & Analytics', 3, 40, 0.85, true),
  ('acf8d363-ab47-409a-87fc-99c0da50181c', '11111111-1111-1111-1111-111111111111', 'GAC-023', 'Sultan Al-Mansour', 'Senior Analyst', 'Sector Advisory', 2, 40, 0.85, true),
  ('582d17a0-5c2f-46e2-aa2e-87475b045092', '11111111-1111-1111-1111-111111111111', 'GAC-024', 'Haya Al-Dossary', 'Analyst', 'Policy & Research', 1, 40, 0.85, true),
  ('55568492-0fb6-4307-a7f2-08f5417914fd', '11111111-1111-1111-1111-111111111111', 'GAC-025', 'Rashid Al-Ateeqi', 'Consultant', 'Program Management', 3, 40, 0.85, true),
  ('498e280a-8ef4-468f-858e-95580f69b78d', '11111111-1111-1111-1111-111111111111', 'GAC-026', 'Nawaf Al-Buqami', 'Analyst', 'Economics', 1, 40, 0.85, false)
on conflict do nothing;

-- Tie the consultant demo account to its resource profile ---------------
update public.profiles set resource_id = '329bad2e-a232-4a77-8358-aa1350d06e09' where id = '22222222-2222-2222-2222-222222222203';

-- Resource skills ---------------------------------------------------------
insert into public.resource_skills (id, organization_id, resource_id, skill_id, proficiency, years_experience, verified) values
  ('6004fb36-750d-4737-b397-dc49fa5174e7', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 4, 5.0, true),
  ('bce3cd49-e01c-4878-93c4-fa3eaa452cc3', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 4, 5.4, false),
  ('a520d911-55a0-4ac6-aef1-2ba53965d8f6', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', '4697eeca-7e39-4d4b-b9e4-6b70c5f34585', 4, 6.0, false),
  ('1bf19fc0-1f80-4674-a749-d3439b7bc4c9', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 3, 5.5, true),
  ('fbd6ca81-8860-4c52-b65b-5a393060c547', '11111111-1111-1111-1111-111111111111', '291e2509-525f-4b4c-b692-e85d58e87baf', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 5, 6.1, false),
  ('54b6194a-820c-4bb3-94c7-414af853ece5', '11111111-1111-1111-1111-111111111111', '291e2509-525f-4b4c-b692-e85d58e87baf', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 4, 6.4, true),
  ('02ab18e8-6bb5-4988-baaa-48ebc43d6650', '11111111-1111-1111-1111-111111111111', '291e2509-525f-4b4c-b692-e85d58e87baf', '8afcef81-f811-417d-bb65-25033e2bd3c2', 5, 6.1, false),
  ('58ca2ba7-4b26-4cce-94fc-c1b335ccbdb8', '11111111-1111-1111-1111-111111111111', '291e2509-525f-4b4c-b692-e85d58e87baf', 'fe107564-9451-40cc-8419-6b70b075f7ac', 5, 7.0, true),
  ('3a5353cd-b0f7-44b3-929b-f29d3a734492', '11111111-1111-1111-1111-111111111111', '60de1196-ab57-4caf-b9dd-f747edb274d5', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 3, 4.2, false),
  ('48561e86-d9db-46cd-a4a9-d6b3ebf91546', '11111111-1111-1111-1111-111111111111', '60de1196-ab57-4caf-b9dd-f747edb274d5', '00431c02-9264-48b6-a566-434e2930bcfc', 3, 3.4, false),
  ('e1ef669a-0bc8-45d8-96aa-c541296533b5', '11111111-1111-1111-1111-111111111111', '60de1196-ab57-4caf-b9dd-f747edb274d5', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 4.7, true),
  ('bc345e26-d13d-4506-9f2d-f50bfa7d9894', '11111111-1111-1111-1111-111111111111', 'ce003944-aa2b-47c2-820d-bf2da66afbd2', '5285b115-c057-4efa-981a-982d21df9fa6', 5, 8.9, true),
  ('eed2f61c-0119-414d-a22f-8b578f384e6c', '11111111-1111-1111-1111-111111111111', 'ce003944-aa2b-47c2-820d-bf2da66afbd2', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 5, 7.7, true),
  ('ad3e8be0-579d-43a0-a3ed-86d6bc7b15a9', '11111111-1111-1111-1111-111111111111', 'ce003944-aa2b-47c2-820d-bf2da66afbd2', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 5, 9.4, false),
  ('8fbaa90a-97a0-405f-9e4a-52c708302585', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 4, 6.3, false),
  ('054c3a66-2b10-4e61-8cd7-0164dfebd710', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 6.4, false),
  ('7d01ab53-f41e-45d1-8df5-a7ff5e198a4a', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '8afcef81-f811-417d-bb65-25033e2bd3c2', 4, 4.9, true),
  ('c5c772e0-6764-4985-8517-ee7b0c3ca2d5', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', '17e54823-8ecb-451e-9672-981659219b83', 5, 6.7, true),
  ('bf867bb5-3e87-48ac-9c24-6cda94b59d30', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 7.5, false),
  ('37ba20a6-8958-4532-a8b4-c16b89ae0dc9', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 4, 7.7, true),
  ('917b040a-1544-4697-b3ae-591449c8a878', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 5, 7.8, true),
  ('9c8b2b9f-50e5-422d-a8d0-5ccd26053766', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 5, 6.6, false),
  ('4ad6dd87-8231-4aba-9dac-f8f0fa6ab821', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', '5be9b3b2-f502-4193-8ce2-d887c6e4f7de', 3, 3.3, true),
  ('d13b6f62-76c3-44bc-8626-78ca7c7da5d5', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 2, 4.4, true),
  ('20224f0f-5e45-4110-ab03-82b08d135bfe', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 2, 3.8, false),
  ('06ed2f7e-33ed-489e-a79a-7f8ac5b7d8e7', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 3, 3.7, false),
  ('1931a1b2-a8bd-4f7f-be15-dc218f187338', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 3, 4.8, false),
  ('2b932bbc-e814-49d5-9ccc-103a51c8ab9a', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', 'fe107564-9451-40cc-8419-6b70b075f7ac', 4, 5.8, true),
  ('e074b8ad-bd80-4ae5-995d-9e5bd73f4c96', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 4, 4.9, true),
  ('18382dac-cb0c-4559-b6e2-57941e416ae0', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', '8afcef81-f811-417d-bb65-25033e2bd3c2', 3, 4.9, false),
  ('ab18735a-fabf-44d4-abe1-ae7482d7ea3f', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 4, 5.9, false),
  ('971b7cf5-c4fd-4928-9122-f6438a20b91e', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 3, 5.2, false),
  ('8a8cdada-2471-4c35-be5a-0c6a41a930c1', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 2, 3.3, true),
  ('aae5ce74-bd62-41b7-b61d-30d3472c1e07', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 2, 3.8, true),
  ('36b08e87-03ef-49e3-b5a1-38f1abfc4ff9', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', '14181039-cd7e-4aa5-a970-ef5addc528ac', 2, 4.4, false),
  ('ad03ea19-86fc-4a82-b777-0efd1a1419d6', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 5.7, false),
  ('1560e4cb-631e-44bb-957a-f3c25808e6d1', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 5.1, false),
  ('ac067071-ffaf-4792-b429-d41514ceb2cf', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 4, 4.9, false),
  ('abcdae35-ed30-4e9c-8a2a-0aee776a5cc2', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 4, 5.1, false),
  ('f9a35a5b-db9a-4901-a375-b938d605b8f6', '11111111-1111-1111-1111-111111111111', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', '17e54823-8ecb-451e-9672-981659219b83', 5, 8.3, true),
  ('1f386efc-4e12-410b-8914-32cf8340cadc', '11111111-1111-1111-1111-111111111111', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 5, 9.1, true),
  ('071d4958-3df5-48c4-be15-bdd7afa738a3', '11111111-1111-1111-1111-111111111111', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 5, 9.2, true),
  ('1ce50fa6-e259-4ead-ab72-452ab6a52961', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 2, 3.8, true),
  ('c921ad49-1a6c-4d41-b388-1ec2512ca782', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', '5285b115-c057-4efa-981a-982d21df9fa6', 3, 4.0, true),
  ('bb35c2f8-9047-4f35-9b62-585296e623da', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 3, 4.5, false),
  ('a47c3848-4019-431f-9813-4d1db7ec9c4e', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 2, 3.3, true),
  ('e518734d-91f4-4d2d-8443-50bb21430a14', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 3, 4.5, true),
  ('dc039280-0bd3-483c-80ed-1e617b45a781', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', '8afcef81-f811-417d-bb65-25033e2bd3c2', 4, 7.8, true),
  ('c0b4e469-ebff-496a-865a-9026f1645091', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 4, 7.9, true),
  ('c0b28518-05f9-43db-a08a-fc4ab8f82251', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 7.7, false),
  ('826a5b09-5e35-4de8-85b3-90a1dd8da54e', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', '14181039-cd7e-4aa5-a970-ef5addc528ac', 4, 6.0, false),
  ('f7553a5e-4e3c-412b-a543-dd45fea031c8', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 5, 7.5, true),
  ('bd6a2e9c-398c-4b07-9cab-237a6865af98', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 3, 5.1, true),
  ('e336d06f-b3aa-4c7f-95e5-7765e3f07696', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 5.9, true),
  ('33385970-d56d-440e-93b3-7431431308a3', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 4, 4.9, true),
  ('7b2f3c38-005a-4422-88cb-23a1ed5dc4b5', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', '5be9b3b2-f502-4193-8ce2-d887c6e4f7de', 4, 5.4, true),
  ('74c90c0b-d489-4c0b-a3cc-d86e7693e4df', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', '4697eeca-7e39-4d4b-b9e4-6b70c5f34585', 3, 5.4, false),
  ('15fc1ab8-f5e9-4ff6-8f72-8c9153538d25', '11111111-1111-1111-1111-111111111111', '6dbf8915-6425-4d5b-902e-aa14822c7092', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 3, 4.1, true),
  ('1a5c20ee-ac52-46d9-8be0-c9f2e5d94a24', '11111111-1111-1111-1111-111111111111', '6dbf8915-6425-4d5b-902e-aa14822c7092', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 2, 3.3, false),
  ('87932d69-6ac2-4444-a413-deb20c66f354', '11111111-1111-1111-1111-111111111111', '6dbf8915-6425-4d5b-902e-aa14822c7092', 'fe107564-9451-40cc-8419-6b70b075f7ac', 2, 4.9, false),
  ('288caeb6-c860-4b1e-85e0-58b0509f1348', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 4, 6.5, true),
  ('0fa5d9f7-1398-4763-b9f1-8936b6a9afba', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 5, 6.2, true),
  ('8a2d1f8c-8437-49f8-84de-587d6e3bbc4c', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '00431c02-9264-48b6-a566-434e2930bcfc', 5, 7.3, true),
  ('7a395701-1ce4-4bc1-9a61-d973b9465d7f', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 5, 7.6, true),
  ('53d8e83f-3492-473e-9d79-1dd116dc87e9', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 4, 6.2, false),
  ('62a902b8-7349-4253-ad8c-3bcde8bbd56f', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 4, 6.5, false),
  ('564819b5-0c52-4769-b9ec-778a41273db0', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 3, 5.2, false),
  ('4f768cb8-054c-4d86-ac71-564499b96034', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 5.6, false),
  ('503078a3-1084-459e-94dc-5d80823f3211', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 4, 5.6, true),
  ('f42bcf15-1bfb-4ec6-8480-965739753afb', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', '5285b115-c057-4efa-981a-982d21df9fa6', 3, 5.5, true),
  ('80cdfcb5-f7f2-4fe8-a84a-e2a5ba45ecc0', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 4, 5.9, true),
  ('a17380f3-2e0b-42d8-bb33-c82c2908a35c', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 4, 6.4, true),
  ('9704a591-35c9-4697-8c93-eeea06ac4cce', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 4, 5.1, true),
  ('3c5db91e-8b86-46f5-8292-7c9223abb654', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 2, 3.7, true),
  ('248a0b9d-104d-4ddf-beb0-b47601cd7ff4', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', '14181039-cd7e-4aa5-a970-ef5addc528ac', 3, 4.2, true),
  ('50d5c7fb-7f31-4131-8d03-c522cab32382', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', '8afcef81-f811-417d-bb65-25033e2bd3c2', 3, 3.3, false),
  ('76da8bd5-3f13-4b35-ab0b-782010fe8c3d', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 3, 4.0, false),
  ('f97cb8dd-0d11-4cb3-a0fb-69506f45580b', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 4.5, true),
  ('5c72d6c2-408f-42fd-9cc9-14b3748a1fae', '11111111-1111-1111-1111-111111111111', 'bf9be801-eaa5-4854-a0fe-6d1146343c50', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 4.6, true),
  ('1ae18be7-7b8b-4c97-a5ca-32f511322c11', '11111111-1111-1111-1111-111111111111', 'bf9be801-eaa5-4854-a0fe-6d1146343c50', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 4, 5.9, true),
  ('431c4d0f-bf30-4b7e-8ead-988a780a9c5c', '11111111-1111-1111-1111-111111111111', 'bf9be801-eaa5-4854-a0fe-6d1146343c50', '14181039-cd7e-4aa5-a970-ef5addc528ac', 3, 5.7, true),
  ('db44668f-b3dd-4dc8-9c31-f5a3fd8c3c44', '11111111-1111-1111-1111-111111111111', 'bf9be801-eaa5-4854-a0fe-6d1146343c50', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 4.6, false),
  ('cdd959ed-0a2d-4804-9647-478b64241ebc', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 5, 7.4, false),
  ('4d49efe4-c97a-4ee7-915b-0d8f06d6fa48', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 4, 6.5, true),
  ('147c5e9f-4f9e-419d-9771-183542d12ebb', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 4, 7.7, true),
  ('bcfdc42e-feb6-437d-be51-f3d027feb76d', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', '8afcef81-f811-417d-bb65-25033e2bd3c2', 3, 5.1, false),
  ('4660eb68-8c6d-43a9-ad37-19d8277af25a', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', 'fe107564-9451-40cc-8419-6b70b075f7ac', 4, 5.5, true),
  ('22a1c435-bbff-493a-9ab9-007a776d4a5c', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 4, 4.7, true),
  ('009eac56-4682-43e3-b3ce-e7f2049016a1', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 4, 6.3, false),
  ('6a9c1668-a7de-44a4-84cc-57af9d2ccaa8', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 3, 4.6, false),
  ('c255f163-c488-4a3e-a7de-cd09f1d9f734', '11111111-1111-1111-1111-111111111111', 'acf8d363-ab47-409a-87fc-99c0da50181c', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 3, 3.7, true),
  ('f374bb4e-5090-4aff-93ee-aeb15b0392a0', '11111111-1111-1111-1111-111111111111', 'acf8d363-ab47-409a-87fc-99c0da50181c', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 2, 4.5, true),
  ('2e930bc0-bd36-4d43-9e30-6e09281ddc97', '11111111-1111-1111-1111-111111111111', 'acf8d363-ab47-409a-87fc-99c0da50181c', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 2, 3.4, true),
  ('02a3967e-aa1e-4336-9b96-0ee8ef389f14', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', '00431c02-9264-48b6-a566-434e2930bcfc', 2, 3.1, true),
  ('cd2196ed-1271-4767-bdb1-efb9b277a90b', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 2, 1.9, false),
  ('b4da27af-e161-495b-8004-925dc969158d', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 2, 2.8, false),
  ('36f0921b-4182-4c65-89ed-7133a35414bc', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 2, 2.0, false),
  ('39a80400-eeb4-4587-a110-316351945120', '11111111-1111-1111-1111-111111111111', '55568492-0fb6-4307-a7f2-08f5417914fd', '8afcef81-f811-417d-bb65-25033e2bd3c2', 4, 6.0, false),
  ('986739c0-ddf5-4989-8e95-03ed256edfb2', '11111111-1111-1111-1111-111111111111', '55568492-0fb6-4307-a7f2-08f5417914fd', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 4, 5.7, false),
  ('2ee726d5-e420-4995-94f1-3a2ac724a5c2', '11111111-1111-1111-1111-111111111111', '55568492-0fb6-4307-a7f2-08f5417914fd', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 3, 5.2, true),
  ('1703bee9-6519-4b36-9670-a7eac0e0f03f', '11111111-1111-1111-1111-111111111111', '55568492-0fb6-4307-a7f2-08f5417914fd', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 4, 5.0, true),
  ('f357d4bf-e29d-41e1-8352-3001a23eb9d4', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 2, 1.7, false),
  ('4ceadec7-a665-4071-9245-81d7738f6a1a', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 2, 1.9, true),
  ('4295317a-14fd-476c-85f6-a1b5e5c9fd2a', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 2, 2.7, true),
  ('845a762c-66b6-4278-9a0c-836c3c6ad99f', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', '5285b115-c057-4efa-981a-982d21df9fa6', 2, 1.8, true)
on conflict do nothing;

-- Historical projects ------------------------------------------------------
insert into public.historical_projects (id, organization_id, resource_id, project_name, sector, project_type, start_date, end_date, performance_score) values
  ('94100597-24c1-474a-a71d-a5f77e69191f', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', 'Education Economic Study Engagement 0-0', 'Finance', 'Operating Model', '2025-09-17', '2025-12-04', 77),
  ('a59d6825-5ae6-413f-a601-f353e8ce0ef0', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', 'Energy Benchmarking Engagement 0-1', 'Finance', 'Benchmarking', '2025-07-03', '2025-09-04', 84),
  ('bdf07068-c500-47b4-b950-6551b437a515', '11111111-1111-1111-1111-111111111111', '329bad2e-a232-4a77-8358-aa1350d06e09', 'Healthcare Transformation Engagement 0-2', 'Digital Government', 'Economic Study', '2026-02-17', '2026-06-16', 92),
  ('f8c93fa5-77fa-4dbc-af04-faa8bfec4983', '11111111-1111-1111-1111-111111111111', '291e2509-525f-4b4c-b692-e85d58e87baf', 'Finance Operating Model Engagement 1-0', 'Finance', 'Operating Model', '2025-05-20', '2025-09-06', 86),
  ('01971238-99b5-4f7e-87ad-a43be8b9272e', '11111111-1111-1111-1111-111111111111', '60de1196-ab57-4caf-b9dd-f747edb274d5', 'Digital Government Strategy Engagement 2-0', 'Finance', 'Economic Study', '2025-03-20', '2025-05-19', 96),
  ('f1835a17-ddeb-4719-945f-c59187b38569', '11111111-1111-1111-1111-111111111111', 'ce003944-aa2b-47c2-820d-bf2da66afbd2', 'Finance Strategy Engagement 3-0', 'Education', 'Operating Model', '2025-05-04', '2025-09-22', 82),
  ('b7b82bc3-8d86-4d19-abd0-98940c08ba66', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', 'Digital Government Operating Model Engagement 5-0', 'Energy', 'Transformation', '2025-02-26', '2025-05-07', 83),
  ('73f6a448-e089-4e3b-9815-a6d11bb9db2a', '11111111-1111-1111-1111-111111111111', 'f348c6f9-f853-46c8-b26f-b66526236198', 'Healthcare Operating Model Engagement 5-1', 'Finance', 'Economic Study', '2026-03-05', '2026-07-24', 85),
  ('bc5400a6-9225-4c5f-8511-d33c8c603d2e', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', 'Energy Transformation Engagement 6-0', 'Energy', 'Transformation', '2025-01-08', '2025-05-07', 96),
  ('36f8e1db-7930-4bde-9582-eecdad903ff9', '11111111-1111-1111-1111-111111111111', '89560178-7e10-43ad-a06b-a6d14bee71af', 'Healthcare Transformation Engagement 6-1', 'Healthcare', 'Operating Model', '2025-01-28', '2025-04-12', 94),
  ('d0c1b08c-4893-4a8d-a179-e29c859fd8d3', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', 'Energy Operating Model Engagement 7-0', 'Energy', 'Economic Study', '2025-02-14', '2025-05-14', 77),
  ('632da767-5af5-4701-9400-a7e4e9c52c44', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', 'Digital Government Strategy Engagement 7-1', 'Healthcare', 'Benchmarking', '2025-12-21', '2026-03-24', 87),
  ('5248eee3-2f25-439f-a141-497bae0c5051', '11111111-1111-1111-1111-111111111111', '64cb761a-5fe9-446d-ac33-dffc2278232d', 'Energy Operating Model Engagement 7-2', 'Digital Government', 'Economic Study', '2025-09-03', '2025-12-29', 70),
  ('c3eec06f-b5c1-4306-8db0-c5a5bdb6f0fd', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', 'Education Transformation Engagement 8-0', 'Finance', 'Benchmarking', '2024-12-27', '2025-03-19', 93),
  ('04606472-214e-41b1-ba45-6e5fd0c5fd6e', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', 'Finance Operating Model Engagement 8-1', 'Energy', 'Strategy', '2025-04-28', '2025-07-25', 86),
  ('a4f0174b-c911-4e04-9625-9ae9517a3713', '11111111-1111-1111-1111-111111111111', '1c19ae02-200e-44fa-abf9-0029422e6df2', 'Digital Government Operating Model Engagement 8-2', 'Education', 'Transformation', '2026-01-31', '2026-05-28', 80),
  ('c53ce786-cda9-4b27-9c17-a7fc74931861', '11111111-1111-1111-1111-111111111111', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', 'Transport Economic Study Engagement 10-0', 'Digital Government', 'Operating Model', '2025-12-15', '2026-05-11', 85),
  ('ae860458-c8a2-44a8-ad1b-36394237b642', '11111111-1111-1111-1111-111111111111', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', 'Digital Government Strategy Engagement 10-1', 'Healthcare', 'Strategy', '2025-04-28', '2025-09-15', 95),
  ('e96d64a2-2b58-438e-ac63-0c505c562404', '11111111-1111-1111-1111-111111111111', 'cb21478c-9a36-47b7-a918-5ff533152bc5', 'Healthcare Economic Study Engagement 11-0', 'Education', 'Strategy', '2026-02-20', '2026-06-07', 81),
  ('9f6a44e8-fd2b-4e6b-9c16-35fb5805f770', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', 'Digital Government Economic Study Engagement 12-0', 'Healthcare', 'Economic Study', '2025-09-18', '2025-12-04', 86),
  ('2399d17a-b9c2-47ab-acc0-a60884431dac', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', 'Finance Operating Model Engagement 12-1', 'Finance', 'Operating Model', '2025-01-08', '2025-04-30', 75),
  ('bdd07511-7f7f-4ae6-810a-c4ca00ab2147', '11111111-1111-1111-1111-111111111111', '2225dfe0-1120-4655-a956-1d2d77622bcf', 'Digital Government Benchmarking Engagement 12-2', 'Energy', 'Transformation', '2026-01-01', '2026-05-04', 82),
  ('6f51dd90-cc9c-4589-95cb-945b3d8d33ca', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', 'Energy Transformation Engagement 13-0', 'Digital Government', 'Benchmarking', '2025-09-21', '2026-01-18', 95),
  ('01fc29de-02a0-41eb-bc1d-8efba281c08b', '11111111-1111-1111-1111-111111111111', '1815f820-f21a-4b99-868d-ccfc5290cf96', 'Transport Strategy Engagement 13-1', 'Transport', 'Transformation', '2025-06-28', '2025-11-17', 84),
  ('74624efc-d7a3-4183-82c3-ad804b660ae4', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', 'Education Transformation Engagement 15-0', 'Transport', 'Transformation', '2026-02-27', '2026-06-25', 76),
  ('f26bc3ec-a753-4352-b5a8-d011f615cb9d', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', 'Education Benchmarking Engagement 15-1', 'Transport', 'Benchmarking', '2024-11-22', '2025-02-17', 96),
  ('7fbb1fc2-a598-4321-b536-0e1c78cf9060', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', 'Education Benchmarking Engagement 15-2', 'Finance', 'Strategy', '2025-04-30', '2025-07-27', 85),
  ('d005034f-eb9e-4c44-bc36-55e7111cdf99', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'Energy Operating Model Engagement 16-0', 'Energy', 'Operating Model', '2025-04-14', '2025-07-31', 87),
  ('2b347e8e-5eba-4200-8ddd-8954aca57df1', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'Education Economic Study Engagement 16-1', 'Finance', 'Strategy', '2025-07-25', '2025-11-14', 70),
  ('a5b82fc1-e22e-4433-aaa7-e7bacdf2d646', '11111111-1111-1111-1111-111111111111', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'Transport Strategy Engagement 16-2', 'Healthcare', 'Economic Study', '2025-03-19', '2025-06-21', 77),
  ('4bebbaff-0236-45ea-aa67-4657c48e06c7', '11111111-1111-1111-1111-111111111111', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', 'Healthcare Economic Study Engagement 17-0', 'Transport', 'Benchmarking', '2025-07-23', '2025-11-22', 87),
  ('330caee7-026c-4de1-b523-a98c3032440b', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', 'Finance Transformation Engagement 18-0', 'Healthcare', 'Strategy', '2025-09-16', '2026-01-09', 79),
  ('62523a0d-d1e1-422b-9b39-4daa5938206c', '11111111-1111-1111-1111-111111111111', 'fe210665-1612-4518-988a-230a8936c1eb', 'Energy Operating Model Engagement 18-1', 'Transport', 'Economic Study', '2024-12-22', '2025-05-08', 87),
  ('3a50d365-a7d5-4f9d-aa54-c0da99db69c9', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', 'Finance Strategy Engagement 20-0', 'Energy', 'Operating Model', '2024-11-24', '2025-02-28', 74),
  ('e1c0ff33-7202-4605-882e-2daa08b433ef', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', 'Healthcare Operating Model Engagement 20-1', 'Education', 'Operating Model', '2026-02-20', '2026-07-07', 97),
  ('5d8a903e-ae4c-4b04-ae72-0eae42503067', '11111111-1111-1111-1111-111111111111', '30e85f72-9270-41d4-8a6e-c02df504f394', 'Education Transformation Engagement 20-2', 'Energy', 'Strategy', '2025-06-20', '2025-10-18', 76),
  ('d83c1f5f-b174-4c6d-99bc-acfdae6d05f1', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', 'Education Operating Model Engagement 21-0', 'Transport', 'Benchmarking', '2025-08-28', '2025-12-29', 79),
  ('9aba4ade-eeab-495c-ad0b-254054926bb1', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', 'Energy Benchmarking Engagement 21-1', 'Education', 'Operating Model', '2025-04-21', '2025-09-06', 84),
  ('a44131bd-c869-4bd8-a5a0-df00335bc1cc', '11111111-1111-1111-1111-111111111111', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', 'Finance Transformation Engagement 21-2', 'Transport', 'Operating Model', '2025-03-10', '2025-06-29', 71),
  ('2540a7da-b026-4a77-8c6b-47743f5638eb', '11111111-1111-1111-1111-111111111111', 'acf8d363-ab47-409a-87fc-99c0da50181c', 'Finance Economic Study Engagement 22-0', 'Education', 'Operating Model', '2026-02-13', '2026-04-24', 80),
  ('f9e6af1c-02fb-4b97-a631-3382bbe35a3d', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', 'Finance Economic Study Engagement 23-0', 'Transport', 'Operating Model', '2025-03-12', '2025-06-19', 77),
  ('95e8ac6f-79bc-4990-ad52-c2c4a7555d5e', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', 'Finance Strategy Engagement 23-1', 'Energy', 'Strategy', '2026-01-12', '2026-05-27', 91),
  ('8e04f729-4428-416b-80e1-bed691d69cb7', '11111111-1111-1111-1111-111111111111', '582d17a0-5c2f-46e2-aa2e-87475b045092', 'Education Transformation Engagement 23-2', 'Transport', 'Transformation', '2025-05-26', '2025-07-30', 76),
  ('54bef456-7b84-4c78-91ef-0c5ea076940b', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', 'Healthcare Benchmarking Engagement 25-0', 'Healthcare', 'Benchmarking', '2025-07-27', '2025-11-01', 83),
  ('971b1c19-d984-4966-a24f-e5400bcf7bf8', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', 'Energy Economic Study Engagement 25-1', 'Transport', 'Strategy', '2025-08-21', '2025-10-21', 75),
  ('077cf3fa-17bc-437c-8145-4809cccef589', '11111111-1111-1111-1111-111111111111', '498e280a-8ef4-468f-858e-95580f69b78d', 'Energy Transformation Engagement 25-2', 'Energy', 'Benchmarking', '2025-03-30', '2025-08-08', 89)
on conflict do nothing;

-- Resource availability (leave / training) --------------------------------
insert into public.resource_availability (id, organization_id, resource_id, date, available_hours, reason, availability_type) values
  ('ac9f33e9-eb2b-4023-85f8-1d4e339eb0b2', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '2026-09-10', 0, 'Annual leave', 'leave'),
  ('f2b02778-835d-4484-863d-ed3301996574', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '2026-09-13', 0, 'Annual leave', 'leave'),
  ('077931cb-7380-4a0e-8da2-3bbabd2ac013', '11111111-1111-1111-1111-111111111111', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', '2026-09-14', 0, 'Annual leave', 'leave'),
  ('eec71e99-e83e-4ee5-a958-060193fc8d2d', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '2026-09-14', 0, 'Annual leave', 'leave'),
  ('68f295e4-dd71-4539-8355-07e0aa4cfe29', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '2026-09-15', 0, 'Annual leave', 'leave'),
  ('f59b31d5-1360-4a9b-8371-5d7058c2228a', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '2026-09-16', 0, 'Annual leave', 'leave'),
  ('56a9be20-0bce-41c6-8edb-377003a2fe64', '11111111-1111-1111-1111-111111111111', 'bcb6d72f-31a4-41bb-a8cf-46420a2b6dc3', '2026-09-17', 0, 'Annual leave', 'leave'),
  ('b851d307-4420-4dfe-81e5-cf560387c70b', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '2026-09-20', 0, 'Annual leave', 'leave'),
  ('08024e07-6b33-4beb-b8d6-28217e569310', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '2026-09-21', 0, 'Annual leave', 'leave'),
  ('31da73b8-2a92-458e-89ea-c2fc468b5263', '11111111-1111-1111-1111-111111111111', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', '2026-09-22', 0, 'Annual leave', 'leave'),
  ('7bc113c3-4486-4a37-9a05-43d81be13900', '11111111-1111-1111-1111-111111111111', '60de1196-ab57-4caf-b9dd-f747edb274d5', '2026-09-08', 4, 'Government Excellence Program training', 'training')
on conflict do nothing;

-- Work requests -------------------------------------------------------------
insert into public.work_requests (id, organization_id, request_number, title, description, requesting_entity, requester_name, request_type, received_date, requested_deadline, strategic_importance, executive_sponsorship, regulatory_importance, public_impact, dependency_impact, urgency_score, priority_score, priority_level, estimated_effort_hours, complexity, status, created_by) values
  ('95298b9c-5f9d-4db2-b227-48baabcc167d', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0001', 'National Healthcare Sector Strategy Review', 'Requested by Council of Economic and Development Affairs to support strategy study objectives, in coordination with Ministry of Health and National Center for Government Excellence.', 'Council of Economic and Development Affairs', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-07-04', '2026-09-26', 95, 90, 10, 80, 50, 55, 65.75, 'medium', 620, 'high', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('8439b651-f048-4de0-9c3e-9a9e04a19a25', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0002', 'International Competitiveness Benchmarking — National Transport & Logistics Sector', 'Requested by Council of Economic and Development Affairs to support benchmarking objectives, in coordination with Ministry of Transport and Ministry of Investment.', 'Council of Economic and Development Affairs', 'Eng. Mona Al-Tamimi', 'Benchmarking', '2026-08-22', '2026-10-20', 50, 10, 10, 50, 10, 35, 31.50, 'low', 340, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0003', 'Government Operating Model Review — Cross-Ministerial Restructuring', 'Requested by Council of Ministers to support operating model objectives, in coordination with General Secretariat of the Council of Ministers and National Center for Government Excellence.', 'Council of Ministers', 'Dr. Bassam Al-Otaibi', 'Operating Model', '2026-06-29', '2026-11-04', 95, 90, 10, 50, 90, 35, 58.75, 'medium', 780, 'very_high', 'allocated', '22222222-2222-2222-2222-222222222202'),
  ('b8a2c1d7-393f-4762-8297-1f57c0c3d47d', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0004', 'Economic Impact Assessment — National Special Economic Zones Program', 'Requested by Council of Economic and Development Affairs to support economic study objectives, in coordination with Ministry of Investment and Ministry of Economy and Planning.', 'Council of Economic and Development Affairs', 'Dr. Bassam Al-Otaibi', 'Economic Study', '2026-08-09', '2026-09-15', 75, 90, 90, 50, 50, 75, 75.75, 'high', 410, 'high', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('a2914624-3170-4e7a-a89b-bd08a7782dc2', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0005', 'National Cabinet Performance Dashboard Development', 'Requested by General Secretariat of the Council of Ministers to support data & analytics objectives, in coordination with National Center for Government Excellence and Ministry of Economy and Planning.', 'General Secretariat of the Council of Ministers', 'Dr. Fahad Al-Ruwaili', 'Data & Analytics', '2026-08-22', '2026-09-19', 50, 90, 10, 20, 10, 75, 52.50, 'medium', 220, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('0b18ccd8-b4eb-43b1-b126-54c74651696e', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0006', 'Legislative Policy Evaluation — National Labor Market Reform', 'Requested by Shura Council to support policy study objectives, in coordination with Ministry of Human Resources and Social Development.', 'Shura Council', 'Dr. Bassam Al-Otaibi', 'Policy Study', '2026-07-13', '2026-09-01', 75, 10, 90, 80, 50, 100, 74.25, 'high', 360, 'high', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('d50f2391-4c72-4d17-b07b-f4da259441f1', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0007', 'National Citizen Services Transformation Assessment', 'Requested by Council of Economic and Development Affairs to support transformation objectives, in coordination with Digital Government Authority and Ministry of Interior and Ministry of Human Resources and Social Development.', 'Council of Economic and Development Affairs', 'Ms. Areej Al-Harbi', 'Transformation', '2026-08-17', '2026-10-05', 75, 90, 10, 80, 50, 55, 60.75, 'medium', 480, 'high', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0008', 'National Government Digital Maturity Review', 'Requested by General Secretariat of the Council of Ministers to support digital transformation objectives, in coordination with Digital Government Authority and National Center for Government Excellence.', 'General Secretariat of the Council of Ministers', 'Ms. Areej Al-Harbi', 'Digital Transformation', '2026-07-12', '2026-10-25', 50, 10, 10, 20, 10, 35, 28.50, 'low', 260, 'medium', 'submitted', '22222222-2222-2222-2222-222222222202'),
  ('46ff7b84-6a64-4175-a060-c55e331c7b78', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0009', 'National Strategic KPI Framework Design — Cabinet Performance Monitoring', 'Requested by General Secretariat of the Council of Ministers to support strategy study objectives, in coordination with National Center for Government Excellence and Ministry of Economy and Planning.', 'General Secretariat of the Council of Ministers', 'Ms. Areej Al-Harbi', 'Strategy Study', '2026-08-22', '2026-09-30', 75, 90, 10, 50, 50, 55, 57.75, 'medium', 300, 'medium', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('81a85063-4ebb-442f-8c0f-cad4cf74783f', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0010', 'National Productivity & Resource Optimization Study', 'Requested by Council of Economic and Development Affairs to support operations objectives, in coordination with Ministry of Economy and Planning and National Center for Government Excellence.', 'Council of Economic and Development Affairs', 'Dr. Bassam Al-Otaibi', 'Operations', '2026-08-09', '2026-09-11', 50, 10, 10, 20, 10, 90, 45.00, 'low', 250, 'medium', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('13d0f588-27c2-4a8a-89ff-1f02c377815e', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0011', 'National Data Governance Strategy Alignment', 'Requested by Royal Court to support strategy study objectives, in coordination with Ministry of Communications and Information Technology and Digital Government Authority and Ministry of Economy and Planning.', 'Royal Court', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-07-31', '2026-11-14', 95, 90, 90, 50, 90, 35, 70.75, 'high', 700, 'very_high', 'in_progress', '22222222-2222-2222-2222-222222222202'),
  ('690c102b-3746-44cb-a906-3512dce23f36', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0012', 'Cross-Ministerial Change Management Program', 'Requested by Council of Ministers to support change management objectives, in coordination with National Center for Government Excellence.', 'Council of Ministers', 'Dr. Fahad Al-Ruwaili', 'Change Management', '2026-08-06', '2026-10-15', 75, 90, 10, 50, 50, 55, 57.75, 'medium', 390, 'high', 'allocated', '22222222-2222-2222-2222-222222222202'),
  ('9c5828f0-5d46-403b-895a-36bc32e4303e', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0013', 'Regulatory Impact Study — National Fintech Regulatory Framework', 'Requested by Shura Council to support policy study objectives, in coordination with Ministry of Finance and Ministry of Investment.', 'Shura Council', 'Dr. Bassam Al-Otaibi', 'Policy Study', '2026-06-24', '2026-09-17', 75, 10, 90, 50, 50, 75, 63.75, 'medium', 320, 'high', 'under_review', '22222222-2222-2222-2222-222222222202'),
  ('63a35636-59da-4dc7-8e60-a123176f208a', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0014', 'National Public & Stakeholder Consultation Framework', 'Requested by Shura Council to support strategy study objectives, in coordination with General Secretariat of the Council of Ministers and National Center for Government Excellence.', 'Shura Council', 'Mr. Salem Al-Kathiri', 'Strategy Study', '2026-08-10', '2026-10-10', 50, 10, 10, 20, 10, 55, 34.50, 'low', 150, 'low', 'submitted', '22222222-2222-2222-2222-222222222202'),
  ('0f4986fa-c8be-49c2-843c-7d2ac14d84ed', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0015', 'National Resilience Program Governance Health Check', 'Requested by Council of Political and Security Affairs to support program management objectives, in coordination with Ministry of Interior and Presidency of State Security.', 'Council of Political and Security Affairs', 'Dr. Fahad Al-Ruwaili', 'Program Management', '2026-07-05', '2026-09-07', 50, 10, 10, 20, 50, 100, 50.00, 'medium', 180, 'medium', 'at_risk', '22222222-2222-2222-2222-222222222202'),
  ('b3364a14-0510-4dec-834d-dabe11a85b47', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0016', 'National PPP Program Feasibility Study — Priority Sectors', 'Requested by Council of Economic and Development Affairs to support economic study objectives, in coordination with Ministry of Investment and Ministry of Finance.', 'Council of Economic and Development Affairs', 'Dr. Fahad Al-Ruwaili', 'Economic Study', '2026-06-28', '2026-10-30', 75, 90, 90, 50, 90, 35, 65.75, 'medium', 640, 'very_high', 'ready_for_allocation', '22222222-2222-2222-2222-222222222202'),
  ('a300a4de-bacb-4313-8434-eda51d823aa2', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0017', 'National Security Sector Workforce Planning Model Update', 'Requested by Council of Political and Security Affairs to support operations objectives, in coordination with Ministry of Interior and Ministry of Defense.', 'Council of Political and Security Affairs', 'Eng. Mona Al-Tamimi', 'Operations', '2026-06-26', '2026-11-24', 20, 10, 10, 20, 10, 35, 21.00, 'low', 120, 'low', 'draft', '22222222-2222-2222-2222-222222222202'),
  ('39657bed-6ec9-48db-b21c-5b743cf0bafc', '11111111-1111-1111-1111-111111111111', 'REQ-2026-0018', 'National Sector Competitiveness Benchmark — Vision 2030 Priority Sectors', 'Requested by Council of Economic and Development Affairs to support benchmarking objectives, in coordination with Ministry of Investment and Ministry of Economy and Planning.', 'Council of Economic and Development Affairs', 'Dr. Bassam Al-Otaibi', 'Benchmarking', '2026-07-07', '2026-09-23', 50, 10, 10, 50, 10, 75, 43.50, 'low', 280, 'medium', 'in_progress', '22222222-2222-2222-2222-222222222202')
on conflict do nothing;

-- Request skills -------------------------------------------------------------
insert into public.request_skills (id, organization_id, request_id, skill_id, required_level, importance_weight, mandatory) values
  ('bffd3a66-7ae8-4acd-b5a0-62f8cd7ec307', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', '17e54823-8ecb-451e-9672-981659219b83', 4, 1.5, true),
  ('8ce71312-0ff1-45cd-b078-69638853264f', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 3, 1, true),
  ('54610e5d-48cc-48b6-acdf-2b03d52bedb9', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, false),
  ('64edba3a-c8b6-4b9e-b7f5-154a169e409c', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 1, false),
  ('8aba54c6-c849-47cb-a09f-203777a9914f', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 4, 1.5, true),
  ('18231547-6bff-44d2-9747-fe15ef14a929', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 1, true),
  ('d0307fb3-ecb9-4b0a-a105-c15feab7f068', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 3, 1, false),
  ('266ed31a-7448-4aec-8fc5-42fcbcc1f223', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '5be9b3b2-f502-4193-8ce2-d887c6e4f7de', 4, 1.5, true),
  ('292d6185-579b-4266-91c3-3c9d5c5d33d2', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '8afcef81-f811-417d-bb65-25033e2bd3c2', 3, 1, true),
  ('d0da9fc0-edf3-40d2-8d59-e5547568ac8b', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 3, 1, false),
  ('36f17d68-4e64-4233-9bce-b9cfc1a2b3e9', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 4, 1.5, true),
  ('c90ae672-ba66-4694-a7fb-df5f4670a9f7', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', '5285b115-c057-4efa-981a-982d21df9fa6', 3, 1, true),
  ('065fb093-8aef-4924-800c-771f91c0e985', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 3, 1, false),
  ('cd2f7b22-a7cb-44d4-b300-bff928f0b994', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 4, 1.5, true),
  ('74714304-6d06-4d86-93eb-877167c56333', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', 'fe107564-9451-40cc-8419-6b70b075f7ac', 3, 1, true),
  ('6b1e8288-29f0-41a2-8ffe-f6d849ef32e8', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 3, 1, false),
  ('900b9df7-fb6e-4202-b4e9-988cdbda490f', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', '00431c02-9264-48b6-a566-434e2930bcfc', 4, 1.5, true),
  ('7714d923-9bd9-452b-926d-b079397327e9', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 1, true),
  ('e72ee596-2d48-4621-9ae2-57c547030819', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, false),
  ('2f486945-7ac4-44c3-974c-b235ca67d7bf', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 4, 1.5, true),
  ('18f54df9-f67d-4beb-996b-e3cebe1a6c5f', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '4697eeca-7e39-4d4b-b9e4-6b70c5f34585', 3, 1, true),
  ('7bec406f-37bc-43b5-b59a-60febbe94e7d', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '8afcef81-f811-417d-bb65-25033e2bd3c2', 3, 1, false),
  ('cde1583d-a65e-4ecb-81cc-8584808ed34a', '11111111-1111-1111-1111-111111111111', '4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', '84aad79c-80e5-49b0-94e3-8b6c5c51159e', 4, 1.5, true),
  ('7aff0cf0-33a0-485e-84e4-9e04c82794e1', '11111111-1111-1111-1111-111111111111', '4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 3, 1, true),
  ('038b482f-daad-4b04-b6d2-b70059c134e3', '11111111-1111-1111-1111-111111111111', '4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', '33511ddb-d37c-4bd0-9390-224ae2301d6f', 3, 1, false),
  ('e2b82069-433f-4c3a-b6d6-2b794eee1718', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 4, 1.5, true),
  ('041a7db5-cfe0-4ad3-9d27-546badf32008', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, true),
  ('7e074859-c479-47e3-b762-93dce32d0ea5', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 1, false),
  ('e3165c0b-b713-4250-868e-4fb2b2f64cd9', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', '8afcef81-f811-417d-bb65-25033e2bd3c2', 4, 1.5, true),
  ('4e85f1c6-dee6-4aaf-a73d-b9ce22898c4c', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 3, 1, true),
  ('b1786951-9bc5-415b-a4c0-78b16a6376c7', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 3, 1, false),
  ('0f687e73-8b2b-4457-8d10-b9c6101b8784', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 4, 1.5, true),
  ('fe97be46-878a-4772-ba55-917cc1eb1b21', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, true),
  ('f6de9d46-7afa-4412-8a69-a3c493ddb87e', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 1, false),
  ('07c9300d-0d9c-4970-9c62-8b6e3b5325ad', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', '4697eeca-7e39-4d4b-b9e4-6b70c5f34585', 4, 1.5, true),
  ('19f5b153-a133-40ae-bbaa-523524822481', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, true),
  ('69075ee1-e540-407d-b9e5-0fd721bd0b8c', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 1, false),
  ('d968894f-11ee-403e-ab2f-630001afb212', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', '00431c02-9264-48b6-a566-434e2930bcfc', 4, 1.5, true),
  ('ddd34605-91b8-4b1c-b167-aa0227f0b597', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 1, true),
  ('bdcdc470-2079-4e18-a377-c354e925de12', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, false),
  ('37590693-65b6-4491-b3a5-fa8eb5dbab90', '11111111-1111-1111-1111-111111111111', '63a35636-59da-4dc7-8e60-a123176f208a', 'ef35cf3f-7f0c-457b-8e94-fad8180e5665', 4, 1.5, true),
  ('ce871405-f088-4ee6-a5b5-e7db65e41725', '11111111-1111-1111-1111-111111111111', '63a35636-59da-4dc7-8e60-a123176f208a', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, true),
  ('723f6b2a-9186-4c78-8628-034d839e3336', '11111111-1111-1111-1111-111111111111', '63a35636-59da-4dc7-8e60-a123176f208a', '2452a1f9-9e96-48f4-a572-6c5e61e3016c', 3, 1, false),
  ('12d3f308-fd0d-4d37-93d0-83efa6152285', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', '14181039-cd7e-4aa5-a970-ef5addc528ac', 4, 1.5, true),
  ('5e0df01c-7188-429d-a6c3-e3535a06a04d', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 3, 1, true),
  ('e3d2d0a6-954d-4b83-925f-b6c090d2682b', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', '2b47b5f9-41f6-4eea-a36f-486af92ce571', 3, 1, false),
  ('39621043-f4f4-4f81-9970-807620e067c8', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', '1483e1a5-356f-482f-8ce4-ef8e061e5427', 4, 1.5, true),
  ('7dbf41e5-77be-4a7a-97c1-359b7f18beeb', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', '5285b115-c057-4efa-981a-982d21df9fa6', 3, 1, true),
  ('ec8632b8-edab-4c15-98c8-dc9cf0073c8b', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', '496f21dd-27ca-41eb-be0c-dc1a84a34427', 3, 1, false),
  ('00f83e66-0bc1-41aa-86e6-2acdb365ba2e', '11111111-1111-1111-1111-111111111111', 'a300a4de-bacb-4313-8434-eda51d823aa2', '8afcef81-f811-417d-bb65-25033e2bd3c2', 4, 1.5, true),
  ('db313d43-5556-435d-b309-c319735da844', '11111111-1111-1111-1111-111111111111', 'a300a4de-bacb-4313-8434-eda51d823aa2', '4af12cdd-f67c-4411-b499-77defa8cc6b2', 3, 1, true),
  ('624b04db-2063-4691-b065-12c257581ba6', '11111111-1111-1111-1111-111111111111', 'a300a4de-bacb-4313-8434-eda51d823aa2', '1e06f48f-f3b0-4fd5-bca0-579a53fada6f', 3, 1, false),
  ('ef44469d-85a1-489c-a649-6326f422ac1e', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', '94cc928e-58bb-44ab-84f5-39d846d7cb47', 4, 1.5, true),
  ('cb414db0-7486-4c76-ae1d-aaa266c7e6dd', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', 'eb514dca-7bbc-4924-a9ba-13d4c84249e7', 3, 1, true),
  ('64615c14-7ae5-4934-877a-6ed85c264c1f', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', '0e9e6af1-f48d-421c-a9ab-3f19c2eee07b', 3, 1, false)
on conflict do nothing;

-- Deliverables -----------------------------------------------------------------
insert into public.deliverables (id, organization_id, request_id, title, due_date, estimated_hours, status) values
  ('e1246f36-6777-44a0-af65-795522529ec8', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', 'National Healthcare Sector Strategy Review — Diagnostic Report', '2026-09-12', 186, 'in_progress'),
  ('28d9237a-8dc9-49d4-9b3a-21a39912a15b', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', 'National Healthcare Sector Strategy Review — Final Recommendations', '2026-09-26', 248, 'not_started'),
  ('ea795a51-3684-41d6-98a3-71869e38918b', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', 'International Competitiveness Benchmarking — National Transport & Logistics Sector — Diagnostic Report', '2026-10-06', 102, 'in_progress'),
  ('4e56f69c-a743-4eae-84bb-ce9b5e462e17', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', 'International Competitiveness Benchmarking — National Transport & Logistics Sector — Final Recommendations', '2026-10-20', 136, 'not_started'),
  ('64b743e6-6f5b-4a6a-84e3-86ddbcc695a1', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', 'Government Operating Model Review — Cross-Ministerial Restructuring — Diagnostic Report', '2026-10-21', 234, 'in_progress'),
  ('d8fe656b-bf7f-43bb-a6d3-1ac32a9db604', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', 'Government Operating Model Review — Cross-Ministerial Restructuring — Final Recommendations', '2026-11-04', 312, 'not_started'),
  ('c5a9d5bd-9fa9-4444-9609-38204ba40a6e', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', 'Economic Impact Assessment — National Special Economic Zones Program — Diagnostic Report', '2026-09-01', 123, 'in_progress'),
  ('797866fe-6292-4507-804f-5896c2942b2a', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', 'Economic Impact Assessment — National Special Economic Zones Program — Final Recommendations', '2026-09-15', 164, 'not_started'),
  ('af84b780-1bd6-4315-abb4-642fdca76522', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', 'National Cabinet Performance Dashboard Development — Diagnostic Report', '2026-09-05', 66, 'in_progress'),
  ('137cce6b-fefb-4611-b188-24cedc630745', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', 'National Cabinet Performance Dashboard Development — Final Recommendations', '2026-09-19', 88, 'not_started'),
  ('c22f9a52-0ed7-4f4f-8ecc-8edba450e8e2', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', 'Legislative Policy Evaluation — National Labor Market Reform — Diagnostic Report', '2026-08-18', 108, 'in_progress'),
  ('0ab3c130-74b4-4c2b-ba15-2509cf06dfb2', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', 'Legislative Policy Evaluation — National Labor Market Reform — Final Recommendations', '2026-09-01', 144, 'not_started'),
  ('2e1f0267-6719-489c-a58e-2f7af37f8c3f', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', 'National Citizen Services Transformation Assessment — Diagnostic Report', '2026-09-21', 144, 'in_progress'),
  ('7fa9baf6-d6ae-43c3-9fe2-b8600608832a', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', 'National Citizen Services Transformation Assessment — Final Recommendations', '2026-10-05', 192, 'not_started'),
  ('558c3634-c381-4cae-803f-ee94908bacb2', '11111111-1111-1111-1111-111111111111', '4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', 'National Government Digital Maturity Review — Diagnostic Report', '2026-10-11', 78, 'in_progress'),
  ('e7981efa-dc88-41c1-923a-e5041e157065', '11111111-1111-1111-1111-111111111111', '4fce452e-75b8-4e83-8c6d-db0dbdbcfef4', 'National Government Digital Maturity Review — Final Recommendations', '2026-10-25', 104, 'not_started'),
  ('83819f65-a227-4c51-b061-f668b957bd79', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', 'National Strategic KPI Framework Design — Cabinet Performance Monitoring — Diagnostic Report', '2026-09-16', 90, 'in_progress'),
  ('5f224e7e-2709-4dcb-bbe2-b5a5d07558a7', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', 'National Strategic KPI Framework Design — Cabinet Performance Monitoring — Final Recommendations', '2026-09-30', 120, 'not_started'),
  ('42babf69-4f61-4c8d-a234-ab76cf2f8c64', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', 'National Productivity & Resource Optimization Study — Diagnostic Report', '2026-08-28', 75, 'in_progress'),
  ('0e902d41-e84a-4066-b726-464c10dd05a1', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', 'National Productivity & Resource Optimization Study — Final Recommendations', '2026-09-11', 100, 'not_started'),
  ('87a687ed-965c-41f1-b8eb-143ecf9a4efe', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', 'National Data Governance Strategy Alignment — Diagnostic Report', '2026-10-31', 210, 'in_progress'),
  ('cdfa3c08-5c40-4643-92b9-22c4c432924d', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', 'National Data Governance Strategy Alignment — Final Recommendations', '2026-11-14', 280, 'not_started'),
  ('39cfe9d4-cbf4-487e-b41a-242584d5bf33', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', 'Cross-Ministerial Change Management Program — Diagnostic Report', '2026-10-01', 117, 'in_progress'),
  ('5907f372-6951-4cdf-afdd-d94964b74936', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', 'Cross-Ministerial Change Management Program — Final Recommendations', '2026-10-15', 156, 'not_started'),
  ('2f0162cc-649b-478c-9522-d24a946d597b', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', 'Regulatory Impact Study — National Fintech Regulatory Framework — Diagnostic Report', '2026-09-03', 96, 'in_progress'),
  ('02535dda-401f-4b6c-adae-2570da202898', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', 'Regulatory Impact Study — National Fintech Regulatory Framework — Final Recommendations', '2026-09-17', 128, 'not_started'),
  ('3de392d8-1e17-4e59-8907-3612562df814', '11111111-1111-1111-1111-111111111111', '63a35636-59da-4dc7-8e60-a123176f208a', 'National Public & Stakeholder Consultation Framework — Diagnostic Report', '2026-09-26', 45, 'in_progress'),
  ('23b44dfd-558e-4c2e-adcc-bfefcd52f7e7', '11111111-1111-1111-1111-111111111111', '63a35636-59da-4dc7-8e60-a123176f208a', 'National Public & Stakeholder Consultation Framework — Final Recommendations', '2026-10-10', 60, 'not_started'),
  ('1f49a60a-14f2-4e7c-9908-20b9aa8e791c', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', 'National Resilience Program Governance Health Check — Diagnostic Report', '2026-08-24', 54, 'in_progress'),
  ('379a70e5-9905-4991-99df-1a798a7d4015', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', 'National Resilience Program Governance Health Check — Final Recommendations', '2026-09-07', 72, 'not_started'),
  ('c019048f-326b-44ce-94c8-25c6d6225b04', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', 'National PPP Program Feasibility Study — Priority Sectors — Diagnostic Report', '2026-10-16', 192, 'in_progress'),
  ('407e0b7e-c8fd-4887-b73c-b62e24fbd1ef', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', 'National PPP Program Feasibility Study — Priority Sectors — Final Recommendations', '2026-10-30', 256, 'not_started'),
  ('599804e5-e343-47f4-a5d1-e7a55884c8fb', '11111111-1111-1111-1111-111111111111', 'a300a4de-bacb-4313-8434-eda51d823aa2', 'National Security Sector Workforce Planning Model Update — Diagnostic Report', '2026-11-10', 36, 'not_started'),
  ('97957784-6bc4-497d-8a56-3654e48a688d', '11111111-1111-1111-1111-111111111111', 'a300a4de-bacb-4313-8434-eda51d823aa2', 'National Security Sector Workforce Planning Model Update — Final Recommendations', '2026-11-24', 48, 'not_started'),
  ('b89431a8-16ea-495e-a4a8-854a3839dba9', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', 'National Sector Competitiveness Benchmark — Vision 2030 Priority Sectors — Diagnostic Report', '2026-09-09', 84, 'in_progress'),
  ('4f400c87-d2e9-41a3-bb69-c66d31aefd40', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', 'National Sector Competitiveness Benchmark — Vision 2030 Priority Sectors — Final Recommendations', '2026-09-23', 112, 'not_started')
on conflict do nothing;

-- Assignments ----------------------------------------------------------------
insert into public.assignments (id, organization_id, request_id, resource_id, assignment_role, allocation_percentage, allocated_hours, start_date, end_date, status, approved_by, approved_at) values
  ('c28f2d2d-4723-4284-896a-34b09324758f', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '291e2509-525f-4b4c-b692-e85d58e87baf', 'lead', 60, 216, '2026-08-26', '2026-10-25', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('33aa7371-d8f5-4b2c-952a-b50f255d124e', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '291e2509-525f-4b4c-b692-e85d58e87baf', 'contributor', 45, 108, '2026-08-31', '2026-10-15', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('57e927ff-9ba8-44ca-b229-6d48331ce329', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', '291e2509-525f-4b4c-b692-e85d58e87baf', 'contributor', 20, 32, '2026-09-05', '2026-10-05', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('80f71a5d-ea50-4bee-bf29-fbc5a696a376', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', 'lead', 60, 216, '2026-08-26', '2026-10-25', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('7e25d4a8-f3f8-416d-bf71-1ad7e822334a', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850', 'contributor', 45, 108, '2026-08-31', '2026-10-15', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('437c8b59-ea9b-4e5f-ab4b-98b36770e1da', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', '30e85f72-9270-41d4-8a6e-c02df504f394', 'lead', 60, 216, '2026-08-26', '2026-10-25', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('3d4b675c-0274-4b71-bc11-dc2be42e1465', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', '30e85f72-9270-41d4-8a6e-c02df504f394', 'contributor', 45, 108, '2026-08-31', '2026-10-15', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('9bfe3ab9-627f-46a8-bd03-32fbc1219486', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', '30e85f72-9270-41d4-8a6e-c02df504f394', 'contributor', 20, 32, '2026-09-05', '2026-10-05', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('789db979-20db-4dd7-af2a-3f876f7909ad', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', '329bad2e-a232-4a77-8358-aa1350d06e09', 'lead', 40, 96, '2026-08-29', '2026-10-08', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('242d22e1-5429-4209-b0e0-a7fa26b4d206', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', '60de1196-ab57-4caf-b9dd-f747edb274d5', 'contributor', 50, 140, '2026-08-30', '2026-10-19', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('28bcef56-d2b7-4745-a085-85b9e79d4949', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', 'ce003944-aa2b-47c2-820d-bf2da66afbd2', 'contributor', 60, 216, '2026-08-31', '2026-10-30', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('be09dfc0-5b5a-4e95-9818-aa9315e19b3b', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', 'f36a7b8d-7eee-4848-9ba7-c4c09b45e3bf', 'lead', 70, 168, '2026-09-01', '2026-10-11', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('48142901-1c9e-4893-9762-9fcbdc81cb32', '11111111-1111-1111-1111-111111111111', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', 'f348c6f9-f853-46c8-b26f-b66526236198', 'contributor', 40, 112, '2026-09-02', '2026-10-22', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('b174c31e-b728-4ef4-b1a3-c8219628b3c6', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', '89560178-7e10-43ad-a06b-a6d14bee71af', 'contributor', 50, 180, '2026-08-29', '2026-10-28', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('c87ca0b0-e84d-4663-bf10-8c4997e43ab5', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '64cb761a-5fe9-446d-ac33-dffc2278232d', 'lead', 60, 144, '2026-08-30', '2026-10-09', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('c94f97ed-d79b-4cf2-a7d2-465da7935651', '11111111-1111-1111-1111-111111111111', '46ff7b84-6a64-4175-a060-c55e331c7b78', 'cb21478c-9a36-47b7-a918-5ff533152bc5', 'contributor', 70, 196, '2026-08-31', '2026-10-20', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('b41c9e92-f5ef-49b7-8988-6b8090a53179', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', '2225dfe0-1120-4655-a956-1d2d77622bcf', 'contributor', 40, 144, '2026-09-01', '2026-10-31', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('ddf98c81-bf43-4be0-88f7-170c65fc22cc', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', '1815f820-f21a-4b99-868d-ccfc5290cf96', 'lead', 50, 120, '2026-09-02', '2026-10-12', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('db98bd8d-9217-4b06-bc26-e9d5d05ec24a', '11111111-1111-1111-1111-111111111111', '690c102b-3746-44cb-a906-3512dce23f36', '6dbf8915-6425-4d5b-902e-aa14822c7092', 'contributor', 60, 168, '2026-08-29', '2026-10-18', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('def0c29c-0bad-47b9-909b-94a92d426924', '11111111-1111-1111-1111-111111111111', '9c5828f0-5d46-403b-895a-36bc32e4303e', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'contributor', 70, 252, '2026-08-30', '2026-10-29', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('072323b0-af02-4be8-93ec-e2afd17a75b8', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', 'a26e0f86-23d7-4f75-ab41-2c66d49f2410', 'lead', 40, 77, '2026-08-31', '2026-10-10', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('d78168a0-50e9-4ea1-8dd5-2792b39ee1b5', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', 'fe210665-1612-4518-988a-230a8936c1eb', 'contributor', 50, 140, '2026-09-01', '2026-10-21', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('61300963-f88b-4a04-ace6-62458f64634b', '11111111-1111-1111-1111-111111111111', '39657bed-6ec9-48db-b21c-5b743cf0bafc', 'bf9be801-eaa5-4854-a0fe-6d1146343c50', 'contributor', 60, 216, '2026-09-02', '2026-11-01', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('51053b51-7585-43e1-a71a-4e621b9b3569', '11111111-1111-1111-1111-111111111111', '95298b9c-5f9d-4db2-b227-48baabcc167d', '6f87b37c-3af1-462d-9d0d-81ef9e6714a9', 'lead', 70, 168, '2026-08-29', '2026-10-08', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('5f3504e8-2e00-439c-9989-b59bd4f8133a', '11111111-1111-1111-1111-111111111111', '8439b651-f048-4de0-9c3e-9a9e04a19a25', 'acf8d363-ab47-409a-87fc-99c0da50181c', 'contributor', 40, 112, '2026-08-30', '2026-10-19', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('80be07a5-165c-4f35-96d2-504ec4eeab59', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '55568492-0fb6-4307-a7f2-08f5417914fd', 'contributor', 15, 18, '2026-09-03', '2026-09-23', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('ec31b6f7-4813-4810-bd16-3e25d5d85028', '11111111-1111-1111-1111-111111111111', 'b3364a14-0510-4dec-834d-dabe11a85b47', '291e2509-525f-4b4c-b692-e85d58e87baf', 'contributor', 25, 40, '2026-09-02', '2026-09-27', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('179fd4a0-b28a-438e-a1f8-0bfd53d7c918', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', '96b6cac2-edbf-4db4-99d2-adf0d9abde00', 'contributor', 27, 43, '2026-09-02', '2026-09-27', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('6f945c7f-464b-4af3-a008-99ae65bee268', '11111111-1111-1111-1111-111111111111', 'd50f2391-4c72-4d17-b07b-f4da259441f1', 'f348c6f9-f853-46c8-b26f-b66526236198', 'contributor', 16, 26, '2026-09-02', '2026-09-27', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('a650b657-85d0-47bd-8a1e-6250576b0e03', '11111111-1111-1111-1111-111111111111', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', '55568492-0fb6-4307-a7f2-08f5417914fd', 'contributor', 18, 29, '2026-09-02', '2026-09-27', 'active', '22222222-2222-2222-2222-222222222202', now()),
  ('46c6bbef-2673-48d6-a79d-65dca7a99d0c', '11111111-1111-1111-1111-111111111111', '13d0f588-27c2-4a8a-89ff-1f02c377815e', 'ee22173c-63d5-47c0-8cf8-cd09853027cc', 'contributor', 23, 37, '2026-09-02', '2026-09-27', 'active', '22222222-2222-2222-2222-222222222202', now())
on conflict do nothing;

-- Risks -------------------------------------------------------------------------
insert into public.risks (id, organization_id, request_id, risk_type, risk_score, severity, description, active) values
  ('e5734910-92f5-4db7-bedd-d215f52a88d7', '11111111-1111-1111-1111-111111111111', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', 'deadline', 77, 'critical', 'Remaining working days are insufficient for the outstanding scope at the current pace.', true),
  ('2976816c-bcb7-484c-8094-8aff2b319b0e', '11111111-1111-1111-1111-111111111111', '0b18ccd8-b4eb-43b1-b126-54c74651696e', 'capacity', 77, 'high', 'Assigned team is projected to exceed sustainable utilization before the deadline.', true),
  ('6345bb16-3190-44c7-a3b9-6c42de6b00d7', '11111111-1111-1111-1111-111111111111', '81a85063-4ebb-442f-8c0f-cad4cf74783f', 'skill_gap', 75, 'critical', 'One or more mandatory skills are only partially covered by the current team.', true),
  ('efb92f92-4d06-4088-8f0f-cbe6729f19d9', '11111111-1111-1111-1111-111111111111', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed', 'dependency', 77, 'high', 'Deliverable depends on inputs from another in-flight engagement that is itself at risk.', true)
on conflict do nothing;

-- Notifications -------------------------------------------------------------------
insert into public.notifications (id, organization_id, user_id, notification_type, severity, title, message, entity_type, entity_id) values
  ('d6734026-e796-4142-b1ca-921b559a2ca6', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Abdullah Al-Harbi is overloaded', 'Abdullah Al-Harbi is projected above the organization overload threshold based on current assignments.', 'resource', '291e2509-525f-4b4c-b692-e85d58e87baf'),
  ('beb355e0-2bc3-4fa2-bc15-c83d444e4bb4', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Ahmed Al-Amri is overloaded', 'Ahmed Al-Amri is projected above the organization overload threshold based on current assignments.', 'resource', '6b9f2ac8-98b5-4f77-8098-8cbcf44ab850'),
  ('721de63c-9289-41d8-9c33-e1ab23c4b762', '11111111-1111-1111-1111-111111111111', null, 'resource_overloaded', 'critical', 'Majed Al-Shehri is overloaded', 'Majed Al-Shehri is projected above the organization overload threshold based on current assignments.', 'resource', '30e85f72-9270-41d4-8a6e-c02df504f394'),
  ('961f5697-f05c-4470-8e98-049aad5f0dce', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Economic Impact Assessment — National Special Economic Zones Program delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d'),
  ('0b07ce4a-00a0-4590-adc3-4f9460e23ee9', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'Legislative Policy Evaluation — National Labor Market Reform delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', '0b18ccd8-b4eb-43b1-b126-54c74651696e'),
  ('45827cc9-feb8-40f7-b6c5-de4b394cb814', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'National Productivity & Resource Optimization Study delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', '81a85063-4ebb-442f-8c0f-cad4cf74783f'),
  ('7f8001d3-27ad-4a1b-a6c6-1293e7220cf3', '11111111-1111-1111-1111-111111111111', null, 'delivery_risk_high', 'warning', 'National Resilience Program Governance Health Check delivery risk increased', 'Delivery risk moved to High/Critical based on the latest capacity and deadline recalculation.', 'work_request', '0f4986fa-c8be-49c2-843c-7d2ac14d84ed')
on conflict do nothing;

-- Audit trail ----------------------------------------------------------------------
insert into public.audit_logs (id, organization_id, user_id, action, entity_type, entity_id, old_value, new_value, reason) values
  ('401414a0-1450-4db6-8077-27184d2d89f1', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '95298b9c-5f9d-4db2-b227-48baabcc167d', null, '{"status":"draft","title":"National Healthcare Sector Strategy Review"}'::jsonb, null),
  ('7521c843-7257-42bb-8029-d90ad6d30d23', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '8439b651-f048-4de0-9c3e-9a9e04a19a25', null, '{"status":"draft","title":"International Competitiveness Benchmarking — National Transport & Logistics Sector"}'::jsonb, null),
  ('a542d9e9-e321-42e9-94a9-d8e60c67d745', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', 'bc3a2ad3-702a-4f10-b6cf-0a01cf082a28', null, '{"status":"draft","title":"Government Operating Model Review — Cross-Ministerial Restructuring"}'::jsonb, null),
  ('79ca831d-2178-43b2-b57c-c674918a28b8', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', 'b8a2c1d7-393f-4762-8297-1f57c0c3d47d', null, '{"status":"draft","title":"Economic Impact Assessment — National Special Economic Zones Program"}'::jsonb, null),
  ('26253991-06f3-4c12-9419-ac0f606bb0bb', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', 'a2914624-3170-4e7a-a89b-bd08a7782dc2', null, '{"status":"draft","title":"National Cabinet Performance Dashboard Development"}'::jsonb, null),
  ('5e2c29ff-c298-45fd-a200-27865214f97c', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'request_created', 'work_request', '0b18ccd8-b4eb-43b1-b126-54c74651696e', null, '{"status":"draft","title":"Legislative Policy Evaluation — National Labor Market Reform"}'::jsonb, null),
  ('cb738041-de00-4bf5-964b-f694475fde13', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', 'c28f2d2d-4723-4284-896a-34b09324758f', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('3e89f246-8630-49aa-9658-50cf56ed05e4', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '33aa7371-d8f5-4b2c-952a-b50f255d124e', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('1bbd5be5-ce9b-4b46-84f2-3cc867a7c9a2', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '57e927ff-9ba8-44ca-b229-6d48331ce329', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":20}'::jsonb, 'management_decision'),
  ('22d8d75f-0b9d-4d6e-90d3-050e521a3541', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '80f71a5d-ea50-4bee-bf29-fbc5a696a376', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('1730c0ae-0fb0-46f3-b318-dd6057d52599', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '7e25d4a8-f3f8-416d-bf71-1ad7e822334a', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('ec97c46f-5b63-4be5-8a26-44901611481e', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '437c8b59-ea9b-4e5f-ab4b-98b36770e1da', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":60}'::jsonb, 'management_decision'),
  ('cc95bdd9-95b0-4f8a-99cd-f2bb1294a508', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '3d4b675c-0274-4b71-bc11-dc2be42e1465', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":45}'::jsonb, 'management_decision'),
  ('effb7762-3e7a-46fa-831f-790fee8cbd9d', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222202', 'assignment_approved', 'assignment', '9bfe3ab9-627f-46a8-bd03-32fbc1219486', '{"status":"proposed"}'::jsonb, '{"status":"active","allocation_percentage":20}'::jsonb, 'management_decision')
on conflict do nothing;

commit;
